### ISSUE TITLE
Ontology Metadata

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#10]
Aggiungere una sezione nell'Ontology Manager per aggiungere i metadati dell'ontologia. Prevederei di utilizzare le AnnotationProperty "standard" di rdfs e Dublin Core, quindi:

- "rdfs:comment" per la descrizione dell'ontologia
- tutte quelle visibili nello screenshot sotto
<img width="887" alt="Schermata 2020-02-01 alle 18 12 27" src="https://user-images.githubusercontent.com/8250758/73639938-a31a2280-466d-11ea-9309-d457c01db8d4.png">

Queste informazioni possono essere visualizzare nell'Info Widget, eventualmente con una preview della description, se la stessa è molto lunga.

**Comment by NonnonePalmiro** [comment]
Utilizzando l'ontology manager è possibile:
- definire un insieme custom di annotation property ( sezione 'Define new annotation property' nel tab 
   'Annotations')
- Associare all'IRI identificante l'ontologia un insieme qualunque di annotation assertion (Sezione  
   'Ontology Annotations' nel tab 'General')

**Comment by valeriosantarelli** [comment]
Ok perfetto, provato, e funziona. Chiudo.
