### ISSUE TITLE
Aggiornare Logo di Eddy

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#102]
Già che stiamo passando alla versione 3 di Eddy, potrebbe essere un buon momento per introdurre il nuovo logo che Gianluca (sviluppatore di Grapholscape) ha preparato un paio di mesi fa, che è stilisticamente simile a quello proprio di Grapholscape.
Rispetto a quello attuale (che risale ai tempi di Daniele Pantaleone) mi sembra più moderno.

Si tratta quindi di cambiare lo spashscreen iniziale (che posso produrre io), e sostituire l'icona che si vede sulla barra delle applicazioni e quella che si vede quando si sta aprendo un nuovo progetto. Non mi pare che all'interno dell'applicazione il logo si vede in altre parti.

In allegato un archivio con i vari file del logo (sia logo + scritta che solo l'icona del logo stesso), appena faccio lo splashscreen allego anche quello.

[Eddy Logo New.zip](https://github.com/obdasystems/eddy/files/4605500/Eddy.Logo.New.zip)

**Comment by NonnonePalmiro** [comment]
Oltre a quelli già segnalati, il logo mi sembra appaia solo nelle finestre di errore. 
Per quanto riguarda il formato delle immagini (solo per tenere traccia): 
- finora abbiamo lavorato esclusivamente con png;
- per l'icona dell'eseguibile servono eddy.png(Linux), eddy.icns(Mac OS), eddy.ico(Windows);
- per l'icona da associare ai file .graphol servono icone con estensione di cui sopra;
- per Mac OS serve anche icona dmg_eddy.icns da ssociare montaggio immagine disco

**Comment by valeriosantarelli** [comment]
In allegato un nuovo archivio con i seguenti file:

- logo di eddy in 3 misure: 1024 - 512 - 256 (px)
- icona in 9 misure, da 512px a 16px, sia in .png che in .ico.
- icona per file graphol

Manca solo l'.incs credo a questo punto.

[eddy-logo.zip](https://github.com/obdasystems/eddy/files/4667248/eddy-logo.zip)

**Comment by NonnonePalmiro** [comment]
Provo a includere la modifica nella prossima nella prossima release

**Comment by valeriosantarelli** [comment]
Ricapitolo la situazione allo stato attuale su Mac (su altro S.O. non ho avuto modo di verificare):

La vecchia icona va ancora sostituita (con il file icns da produrre) nel seguenti posti:
- Dock bar dal Mac (barra in basso con tutte le applicazioni)
- Splashscreen
- icona di anteprima del file che si vede dal Finder
- cartella Applicazioni del Finder

Inoltre il nuovo logo nella schermata di trascinamento del logo nella cartella Applicazioni si vede enorme, se possibile rimpicciolirlo un pochino.

<img width="1088" alt="Schermata 2020-05-26 alle 08 31 04" src="https://user-images.githubusercontent.com/8250758/83389613-c7ee8e80-a3f0-11ea-83d9-c83ae8499f14.png">

**Comment by NonnonePalmiro** [comment]
Le icone icns possono essere create con XCode, appena ci prendo confidenza le faccio io.

La versione attualmente su drive dovrebbe risolvere il problema dell'immagine di montaggio su mac

**Comment by valeriosantarelli** [comment]
Una osservazione sul logo:
forse sarebbe in generale più carino utilizzare la versione del logo senza la scritta "Eddy", almeno per quel che riguarda l'icona che viene visualizzata nell'elenco delle applicazioni, nel docker, e nella schermata in cui si trascina l'icona dentro la cartella Applicazioni sul Mac.

<img width="84" alt="Schermata 2020-06-16 alle 09 42 54" src="https://user-images.githubusercontent.com/8250758/84746238-f99d5300-afb5-11ea-9bc9-096c08f1d6d0.png">

<img width="430" alt="Schermata 2020-06-16 alle 09 43 00" src="https://user-images.githubusercontent.com/8250758/84746260-002bca80-afb6-11ea-9a07-4bcbff74313b.png">


In generale mi pare che si tenda sempre a utilizzare icone senza scritte in questi casi.

**Comment by NonnonePalmiro** [comment]
Per creare i file icns bisogna partire da una immagine che sia di dimensione 1024x1024, mentre la dimensione più alta delle icone (quelle senza scritta) fornite da Gianluca è 512x512. 

Infatti sono riuscito a creare i file icns solo a partire dall'immagine eddy-logo-1024.png (che ha risoluzione 72x72), mentre ottengo sempre un errore se provo ad utilizzare eddy-icon-512.png (ho anche provato a modificare l'immagine con Gimp per portarla a dimensione 1024x1024 
![eddy_512x512@x2](https://user-images.githubusercontent.com/46748150/84781202-d63ecc00-afe6-11ea-84b6-7d01575fe5c2.png) ma ottengo una risoluzione 57x57 e si vede che il mac la considera troppo bassa).

**Comment by NonnonePalmiro** [comment]
Di seguito il tutorial che ho seguito per la generazione icns. In caso se hai tempo provaci pure tu, magari hai più fortuna
https://www.youtube.com/watch?v=QbVni3ot76U

**Comment by valeriosantarelli** [comment]
Prova con questo.
Ho creato una versione 1024x1024 dell'icona partendo dal sorgente in formato svg usando Inkscape (a proposito, ora c'è proprio una versione per Mac, che è molto utile per sta roba).

[eddyicon.icns.zip](https://github.com/obdasystems/eddy/files/4791122/eddyicon.icns.zip)

**Comment by NonnonePalmiro** [comment]
Perfetto grazie, questa funziona alla grande. Su Drive c'è la versione nuova che usa quest'icona

**Comment by valeriosantarelli** [comment]
Su Windows, nel processo di installazione, viene ancora utilizzata la vecchia icona.

![Cattura](https://user-images.githubusercontent.com/8250758/86233167-53e10b00-bb95-11ea-827d-e6f9c3af67bd.PNG)

![Cattura2](https://user-images.githubusercontent.com/8250758/86233180-57749200-bb95-11ea-8ca4-52da564a18d7.PNG)

**Comment by valeriosantarelli** [comment]
In realtà rivedendoli forse non vanno bene nè l'icona nuova nè il logo nuovo per queste schermate...

**Comment by NonnonePalmiro** [comment]
Ho provato a guardare, ma non sono riuscito a capire come si modificano i menu dell'installer Windows. In caso ricordiamoci di provare a chiedere a Manuel

**Comment by fing-daniele** [comment]
Per modificare i menu dell'installar Windows bisogna cambiare le immagini che utilizza innosetup: https://github.com/obdasystems/eddy/tree/master/support/innosetup 😉

**Comment by danielepantaleone** [comment]
Per modificare i menu dell'installar Windows bisogna cambiare le immagini che utilizza innosetup: https://github.com/obdasystems/eddy/tree/master/support/innosetup 😉
