### ISSUE TITLE
Aggiunta di lingue oltre a quelle di default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#107]
Prevedere la possibilità di aggiungere ulteriori lingue al progetto (potrebbe servire per Almawave-INAIL).

Io ho fatto un tentativo inserendo a mano una nuova lingua nel diagramma, e la vedo in effetti quando faccio edit di una annotation; ma non la vedo nel menu View->Render By.

**Comment by NonnonePalmiro** [comment]
La funzionalità è stata aggiunta sulla versione attualmente su drive per MacOS. 

Al momento le nuove lingue si possono aggiungere solo aggiungendo annotations con tag non ancora nominati. Una volta aggiunte le nuove lingue, queste saranno disponibili nel menu per lo switch delle label.

Al momento, una volta aggiunta una nuova lingua, non è poi possibile rimuoverla dal progetto

**Comment by valeriosantarelli** [comment]
Al momento sta funzionando tutto, tranne una piccolissima cosa: quando scelgo dal menu dello switch una delle lingue nuove, le label vengono visualizzate correttamente, però la lingua scelta non rimane checkata.
Cerco di spiegarmi con uno screenshot.

Ho definito una label "asdfasf" in una nuova lingua "csa", e scelto "csa" dal menu switch. Come vedi, in effetti viene visualizzato tutto correttamente, tranne che nel menu, quando ci ritorno, il check non è su csa.

<img width="745" alt="Schermata 2020-06-18 alle 09 25 35" src="https://user-images.githubusercontent.com/8250758/84990924-1ff1f880-b146-11ea-99a1-df1d0a0bc452.png">

**Comment by valeriosantarelli** [comment]
Riguardo la rimozione della lingua, io non la farei togliere nè ora nè mai.
Se uno proprio non vuole usarla, cancella le annotations in quella lingua, oppure non la sceglie dal menu switch.

Viceversa, se uno permettesse di cancellarla bisognerebbe automaticamente cancellare tutte le label definite in quella lingua, e quindi l'operazione dovrebbe avvenire solo dopo 100mila messaggi di warning.

**Comment by NonnonePalmiro** [comment]
Su Drive c'è la nuova versione per MacOS che dovrebbe risolvere il problema

**Comment by valeriosantarelli** [comment]
Confermo e chiudo.
