### ISSUE TITLE
Rendering in OWL delle Entity con prefisso :

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#108]
Nelle ontologie che usano il prefisso vuoto ":", l'esportazione in OWL produce degli assiomi con questa forma:

```
SubClassOf(<UneditedBook> <Book>)
DisjointClasses(<UneditedBook> ObjectSomeValuesFrom(<hasEdition> owl:Thing))
SubClassOf(ObjectUnionOf(<AudioBook> <E-Book> <PrintedBook>) <Book>)
SubClassOf(ObjectUnionOf(<EconomicEdition> <SpecialEdition>) <Edition>)
DisjointClasses(<AudioBook> <E-Book> <PrintedBook>)
```

Le entities sono incluse tra < >, invece che con il : davanti.

**Comment by valeriosantarelli** [comment]
La issue ancora non è risolta (con build del 24/06/2020).

Al momento non è possibile creare una ontologia con prefisso vuoto (motivo per il quale probabilmente non è emerso fin qui il problema). Invece dovrebbe farlo fare, e poi si dovrebbe vedere il : davanti a tutte le entità associate al namespace assegnate al prefisso.

**Comment by NonnonePalmiro** [comment]
Stessa problematica si riscontra con ontologia Sapientia

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto.  A breve dovrebbe essere disponibile nuovo build su bintray

**Comment by valeriosantarelli** [comment]
Confermo, chiudo.
