### ISSUE TITLE
Entity Node labels

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#11]
- [ ] Prevent the label of a class node from being moved outside the frame of the class node.
- [ ] By default, set the label of a node outside of the role shape (exactly as for attribute). In general, the role shape is so small that any label with prefix will be too big to fit inside, so we might as well place it outside by default.

**Comment by NonnonePalmiro** [comment]
La parte del ruolo è stata fatta. 
La parte relativa alle classi non è banale, siamo sicuri che sia necessario (o comunque che sia da mettere nelle cose da implementare immediatamente) a fronte del nuova modalità di gestione delle etichette?

**Comment by valeriosantarelli** [comment]
No, assolutamente. Per adesso può andare bene così, la cosa importante era l'etichetta del ruolo, che alla fine viene sempre spostata.
