### ISSUE TITLE
Errore traduzione OWL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#111]
C'è un errore (credo analogo a quello della traduzione degli assiomi ObjectPropertyRange) nella traduzione in OWL di questo assiomi Graphol:

<img width="539" alt="Schermata 2020-06-16 alle 09 37 52" src="https://user-images.githubusercontent.com/8250758/84745585-18e7b080-afb5-11ea-8b26-0ef0184168a9.png">

l'assioma che viene prodotto è il seguente:
`EquivalentClasses(sh:Superhero ObjectSomeValuesFrom(sh:is_enemy_of owl:Thing))`

Manca l'ObjectInverseOf applicato al ruolo, visto che si tratta del dominio.

La stessa cosa avviene anche se c'è solo la partecipazione obbligatoria. Viene prodotto questo assioma:
`SubClassOf(sh:Superhero ObjectSomeValuesFrom(sh:is_enemy_of owl:Thing))`

**Comment by NonnonePalmiro** [comment]
La versione caricata oggi su Drive dovrebbe risolvere il problema

**Comment by valeriosantarelli** [comment]
Confermo.
