### ISSUE TITLE
I testi di alcuni componenti sono più grandi di altri

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#113]
Sembra verificarsi solo su ambiente linux. Allego screenshot.
**Info Label e IRI di un nodo selezionato**
![Screenshot from 2020-06-24 10-49-36](https://user-images.githubusercontent.com/36189778/85525013-f4b94e80-b608-11ea-91b1-be336f9c5c73.png)
**Ontology Manager**
![Screenshot from 2020-06-24 10-48-33](https://user-images.githubusercontent.com/36189778/85525017-f551e500-b608-11ea-8d74-acf8a9dd3d0b.png)

**Comment by valeriosantarelli** [comment]
Il problema si verifica anche su Windows.

![Cattura](https://user-images.githubusercontent.com/8250758/87135231-1158b600-c29a-11ea-9335-c0a080cca6be.PNG)

@giacomoronconiobda dicevi che secondo te potrebbe essere causato dal tentativo di settare esplicitamente il font nelle caselle che presentano il problema? 

Ho spostato alla 3.1 perchè ho riscontrato anche il problema su Windows, quindi la risoluzione è un pochino più urgente.

**Comment by giacomoronconiobda** [comment]
Su Ubuntu si risolve commentando le righe dove si setta il font 'roboto'.
Non so però se è quello che si vuole

Il ven 10 lug 2020, 10:43 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by mnamici** [comment]
Confermo, è dovuto al set esplicito del font su alcuni pannelli nuovi nella versione 3, a partire dalla v1.2 i font non vengono più settati esplicitamente per ogni componente, ma vengono ereditati dall'applicazione così da rendere possibile la personalizzazione del font a preferenza dell'utente. 

Alcuni di questi riferimenti o mi sono sfuggiti durante il merge o sono stati introdotti successivamente. Ad ogni modo è un fix semplice, lo includiamo nel primo rilascio della v3.

**Comment by valeriosantarelli** [comment]
Ok, benissimo!
