### ISSUE TITLE
Modificare versione di un'ontologia

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#114]
Non sono riuscito a trovare un modo per modificare la versione di un'ontologia.

**Comment by valeriosantarelli** [comment]
Dall'Ontology Manager, la prima voce è la versione.

![Schermata 2020-06-30 alle 16 10 38](https://user-images.githubusercontent.com/8250758/86136360-4a4f9880-baec-11ea-8b9b-6da638f88d66.png)
