### ISSUE TITLE
Search su ontology explorer

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#115]
Errore riscontrato lanciando Eddy da PyCharm, Ubuntu

Se si cerca un'entità nell'ontology explorer non è possibile visualizzare i nodi in cui occorre l'entità
![Screenshot from 2020-07-02 12-33-25](https://user-images.githubusercontent.com/36189778/86348672-43499700-bc60-11ea-865a-5a25292e5a86.png)

**Comment by NonnonePalmiro** [comment]
Su quella vecchia non funzionava così?

**Comment by NonnonePalmiro** [comment]
Ah no i nodi è vero, questo le devo rivedere... Comunque continuo a invitarti a non usare sistemi unix

**Comment by NonnonePalmiro** [comment]
La cosa dovrebbe essere risolta nel prossimo build su bintray
