### ISSUE TITLE
Verificare il Merger rispetto alle ultime modifiche

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#116]
Verificare il funzionamento corretto del merger rispetto agli ultimi interventi effettuati su Eddy, che riassumo qui sotto:

- Dimensione del font per singolo nodo: è ora possibile definire una dimensione diversa del font per ogni entità dell'ontologia
- E' stato aggiunto il supporto per l'assioma OWL HasKey: c'è quindi ora un operatore "key" (solito esagono bianco) che prende in input un nodo di classe (atomica o espressione) e n attributi/ruoli
- Sono state corrette le problematiche che c'erano nella definizione dei datatype restrictions: non so se questo ha un impatto su grapholscape, ma te lo segnalo dato che tu stessi avevi riscontrato dei problemi
- E' stata aggiunta la possibilità di aggiungere nuove lingue oltre a quelle di default: anche qui, forse non c'è nulla da fare in grapholscape, tanto le lingue nuove vanno semplicemente in aggiunta a quelle di default, con la stessa struttura xml
- E' stata aggiunta la possibilità di definire una lingua di default: nel file graphol si trova proprio all'inizio, nel tag "ontology", insieme anche all'IRI dell'ontologia: 
`<ontology addLabelFromUserInput="0" lang="en" iri="http://www.obdasystems.com/books/" addLabelFromSimpleName="0">`
- E' stata estesa la possibilità di definire assiomi di metalivello: adesso si può tracciare un arco instanceOf tra ruoli/attributi e classi

**Comment by NonnonePalmiro** [comment]
Il merger dovrebbe essere a posto
