### ISSUE TITLE
Refactoring di un IRI associata ad un namespace di default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#117]
Il tentativo di fare refactoring sull'IRI "http://www.w3.org/2001/XMLSchema" per reintrodurre il cancelletto alla fine, quindi "http://www.w3.org/2001/XMLSchema#", ha generato l'errore che segue:

```
Traceback (most recent call last):
  File "/Users/travis/build/obdasystems/eddy/eddy/plugins/ontology-explorer/ontology_explorer.py", line 419, in onIRIRemovedFromAllDiagrams
AttributeError: 'NoneType' object has no attribute 'data'
```

L'operazione in realtà è poi andata a buon fine, nonostante l'errore.

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto

**Comment by valeriosantarelli** [comment]
Confermo, chiudo
