### ISSUE TITLE
Errore su apertura "Node IRI"

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#118]
Se faccio click con il tasto destro su una entità e scelgo Node IRI, viene fuori il seguente errore:

`TypeError: doOpenIRIDialog() missing 1 required positional argument: 'node'
`

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto

**Comment by valeriosantarelli** [comment]
Confermo, chiudo.
