### ISSUE TITLE
Inserire un warning su modifica IRI da IRI Builder

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#119]
Attualmente, se si modifica una IRI utilizzando l'IRI Builder, quindi ad esempio facendo doppio-click sul nodo (oppure tasto destro -> Node IRI), si rischia di perdere tutte le annotazioni riferite alla IRI che si sta modificando.
In particolare questo avviene se quella modificata è l'unica occorrenza nell'ontologia dell'IRI.

Il comportamento corretto è supportato da Eddy attraverso la funzionalità di "IRI Refactor", disponibile nel menu contestuale.

Il problema che ravvedo è che se uno questa cosa non la sa (probabilmente abituato alle versioni precedenti di Eddy), sicuramente per modificare una IRI (magari correggendo un typo nel nome ad esempio), quello che farà è doppio-click sul nodo (l'ho fatto anche io!). Quello che suggerirei quindi è di mettere una finestra di warning nell'IRI Builder che viene attivata quando si preme il pulsante Save, che dice una cosa tipo 
```
Warning! By modifying the IRI, all metadata (annotations, properties, etc.) relative to the previous IRI can be lost! 
If you really wanted to just change the IRI of the selected Entity without losing any metadata, please press Cancel now, and do so using the IRI Refactor option, available from the contextual menu of the selected Entity. 
```
Con sotto le opzioni "Cancel" e "Confirm".

Questa cosa credo sia abbastanza fondamentale, ci eviterà una inevitabile pioggia di bestemmie quando la gente comincerà a perdere le descrizioni che ha scritto senza aver fatto backup.

**Comment by NonnonePalmiro** [comment]
Il modo in cui funziona adesso (doppia modalità 'Node IRI' ed 'IRI Refactor') era stato espressamente richiesto perchè in molti casi elementi nuovi dell'ontologia vengono creati copia-incollando elementi già esistenti sul diagramma per poi modificarli piuttosto che trascinare gli elementi dalla palette (altrimenti l'opzione 'Node IRI' potrebbe essere proprio rimossa). Apportando questa modifica, ogni volta che si copia un elemento per poi modificarlo apparirà la finestra di warning (e alla decima volta, giù bestemmie comunque...) 

Credo quindi credo che al massimo la finestra di warning sia da mostrare esclusivamente nel caso in cui stia intervenendo sull'unica occorrenza per evitare la perdita delle annotazioni

**Comment by NonnonePalmiro** [comment]
Si consideri anche che, se si preferisse, nel caso in cui si attivi 'Node IRI' sull'unica occorrenza di una IRI, si potrebbe far scattare lo stesso comportamento dell'azione 'IRI Refactor' spostando le annotazioni da IRI_TO_BE_REMOVED a NEW_IRI

**Comment by valeriosantarelli** [comment]
> Si consideri anche che, se si preferisse, nel caso in cui si attivi 'Node IRI' sull'unica occorrenza di una IRI, si potrebbe far scattare lo stesso comportamento dell'azione 'IRI Refactor' spostando le annotazioni da IRI_TO_BE_REMOVED a NEW_IRI

Ah ok, questo probabilmente risolverebbe il problema del tutto.
Avevo pensato al fatto che sarebbe scocciante sempre il warning, però meglio una bestemmia per un warning in più che uno per una informazione persa.

Ad ogni modo, con questa opzione direi che risolviamo nel modo migliore.
