### ISSUE TITLE
Classe non riportata nell'Ontology Explorer

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#120]
Dopo una serie di azioni che riporto sotto, la classe Sezione_di_censimento dell'ontologia ISTAT RBI non figura più nell'Ontology Explorer.

Questa la successione di azioni (tra la v1.2.4 e la v1.2.5):
- verifica che la classe Sezione_di_censimento era definita, in due nodi diversi ovviamente, sia con prefisso rbi che rsbl, e che quella con prefisso rbi conteneva un errore nella parte di input della IRI (e quindi compariva due volte nell'Ontology Explorer)
- modifica della parte di input della classe Sezione_di_censimento con prefisso rbi: /Sezione_di_censimento -> Sezione_di_censimento
- modifica del prefisso di quest'ultima classe: rbi -> rsbl

Dopo aver effettuato queste operazioni, i due nodi ora rappresentano la stessa classe, ma la classe non figura nell'Ontology Explorer.

![Schermata 2020-10-15 alle 10 08 42](https://user-images.githubusercontent.com/8250758/96095088-6f66ec00-0ece-11eb-83a5-7dd617f9dff0.png)

Aggiungo che dopo aver chiuso il progetto e riaperto, la classe è ora presente nell'Ontology Explorer.

**Comment by NonnonePalmiro** [comment]
Il problema su ISTAT riesco a replicarlo (quindi di sicuro il problema esiste), ma non riesco a riprodurlo su diagrammi nuovi e più piccoli (che si gestiscono in maniera più agile durante il debug) . Tu per caso riesci a riprodurre la problematica su un progetto nuovo con solo due classi?

**Comment by valeriosantarelli** [comment]
Fixato nella versione 3.1.dev0.

Chiudo.
