### ISSUE TITLE
Errore dopo cancellazione prefisso "default"

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#122]
Se dall'ontologia ISTAT in allegato (la RSBL v1.1.0) si elimina il prefisso "rsbl_5", l'operazione viene correttamente eseguita, ma ogni successivo tentativo di inserire un nuovo elemento nel diagramma genere il seguente errore:
```

Traceback (most recent call last):
  File "eddy/core/diagram.py", line 226, in dropEvent
  File "eddy/ui/session.py", line 2464, in doOpenIRIBuilder
  File "eddy/ui/iri.py", line 193, in __init__
  File "eddy/core/owl.py", line 1780, in getNamespace
KeyError: 'rsbl_5'
```

L'errore si verifica solo per questo prefisso, perchè credo che in qualche modo sia quello di default dell'ontologia. E' quello che viene inizialmente proposto quando si aggiunge un elemento all'ontologia. Inoltre, nel file c'è scritto questo:

`<ontology addLabelFromSimpleName="0" prefix="rsbl_5" iri="http://www.datiopen.istat.it/Ontologie/RSBL#" addLabelFromUserInput="1" lang="en">`

[RSBL_EA-v1.1.0.graphol.zip](https://github.com/obdasystems/eddy/files/5493007/RSBL_EA-v1.1.0.graphol.zip)

**Comment by NonnonePalmiro** [comment]
Fixed
