### ISSUE TITLE
Lingua della label quando viene creato un nuovo termine

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#123]
Quando si aggiunge un nuovo elemento all'ontologia tramite l'IRI Builder, la finestra propone la possibilità di derivare la label, e di specificare anche la lingua della label.

![Schermata 2020-11-03 alle 15 15 43](https://user-images.githubusercontent.com/8250758/98217953-7b811f00-1f4b-11eb-9e73-d06143f35790.png)

La lingua di default è inglese, quindi viene proposto "en". Se però da questo menu si cambia la lingua, la modifica non viene registrata: la lingua della label rimane "en".

![Schermata 2020-11-03 alle 15 15 52](https://user-images.githubusercontent.com/8250758/98218278-e03c7980-1f4b-11eb-8ebe-6f6c923115de.png)

![Schermata 2020-11-03 alle 15 16 06](https://user-images.githubusercontent.com/8250758/98218303-e7638780-1f4b-11eb-84c7-7151ffaf2e0c.png)

Poi ovviamente la lingua si può cambiare accedendo da menu contestuale alla voce Annotations, però in prima istanza la selezione della lingua diversa da quella di default non ha effetto.

**Comment by NonnonePalmiro** [comment]
fixed
