### ISSUE TITLE
Malfunzionamento Ricerca

### ISSUE THREAD

**Issue by melenacarbonari** [obdasystems/eddy#124]
la ricerca da explorer non porta agli oggetti cercati all'interno del graphol. Cliccando sia col tasto dx che con il sx  non succede nulla.

Versione Eddy: 3.0.0
SO: Window 10 

![Eddy_Explorer](https://user-images.githubusercontent.com/75839825/101900215-684b1a00-3baf-11eb-983c-51f7c7ce3a6c.JPG)

**Comment by NonnonePalmiro** [comment]
Cortesemente provi a scaricare la versione 3.1 (ancora in fase di sviluppo) disponibile al seguente indirizzo:

https://bintray.com/obdasystems/eddy-builds/download_file?file_path=3.1.dev0%2FEddy-3.1.dev0-windows_amd64.exe

Se le problematiche dovessero persistere, cercheremo di intervenire appena possibile

**Comment by melenacarbonari** [comment]
Grazie, ho provato e succede la stessa cosa, l'errore al termine dei 10 minuti di attesa è sempre relativo alla ricerca degli aggiornamenti, come da immagine allegata. 
![Error_Update_Eddy](https://user-images.githubusercontent.com/75839825/102211396-d48d8c80-3ed3-11eb-973c-41e59b75f3a1.JPG)


Ho quindi re installato la versione 3.0 che ci aveva girato giacomo ronconi il 29/06 reperibile a questo link [https://bintray.com/obdasystems/eddy-builds/Eddy/3.0.0#files/3.0.0/develop](url). Con questa versione i file si aprono in meno di un minuto, la ricerca non funziona se si cerca un elemento, nel senso che lo trova ma non dà possibilità di andare direttamente nel graphol, ma se si scorrono invece gli elementi dall'explorer e si seleziona in questo modo si viene indirizzati all'elemento in tempi brevissimi. 

La versione 3.0 scaricata ieri mattina dal vostro sito e datata 30/09, dà i problemi di tempistica: 9/10 minuti per aprire un file. Ma la ricerca funziona sempre, anche se i tempi anche in questo caso sono molto lunghi. Stessa cosa con la versione beta 3.1. 

A questo punto mi lascio la versione con la ricerca non al 100% ma almeno ho dei tempi ottimali per lavorare. Grazie mille del supporto.

**Comment by mnamici** [comment]
Chiudo in quanto il problema era stato risolto nella release 3.1.
