### ISSUE TITLE
Assiomi OWL di una Entità dell'ontologia

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#127]
Aggiungere una voce al menù contestuale di ciascuna entità dell'ontologia chiamata (ad esempio) "OWL Axioms" che, se selezionata, semplicemente elenca in una finestra tutti gli assiomi OWL, in sintassi funzionale, in cui è coinvolta l'entità stessa.

[Suggerimento di Maurizio]

**Comment by NonnonePalmiro** [comment]
Il grafo non viene tradotto real-time in assiomi  (questo comporterebbe tradurre l'intero grafo ogni volta che viene tolto o aggiunto un elemento, il che porterebbe a un appesantimento micidiale). Di' a Maurizio che al momento non è proprio possibile

**Comment by NonnonePalmiro** [comment]
O meglio, è possibile farlo ma potrebbe essere molto lento visto che dovrebbe calcolare gli assiomi solo dopo il click sul menu contestuale.  A me sembra più una cosa da versione 4.0, quando magari saremo riusciti ad agganciare un reasoner buffering che sia sempre attivo invece di dover tirare su e giù in continuazione i binding con le owl api in java

**Comment by valeriosantarelli** [comment]
Beh si, pensavo infatti facendo tutto dopo il click sul menu contestuale. 
Mi sembra però che i tempi possano essere abbastanza ragionevoli, Eddy è velocissimo a tradurre in OWL da quando siamo passati alla 3.0. 
Ho provato ad esempio a esportare in OWL l'ontologia INAIL, sono 1300 entità circa, e ci mette al massimo un paio di secondi per fare tutto.

Ah, ovviamente mi sto riferendo solo agli assiomi asseriti, non inferiti.

Se tecnicamente però è troppo complicato lo rimandiamo.

**Comment by NonnonePalmiro** [comment]
Non è che sia complicatissimo avere l'insieme degli assiomi, ma è la gestione dell'interazione con questi. Se si vuole un semplice elenco degli assiomi in forma testuale si può anche fare, ma per esempio vi immaginate una finestra modale o meno? 
In effetti per sapere se è fattibile o meno (io forse mi ero immaginato qualcosa di più complicato di quanto richiesto da Maurizio) bisognerebbe indicare precisamente cosa succede quando questo tasto viene premuto e come debba proseguire l'interazione con l'utente
