### ISSUE TITLE
Conteggio errato degli Atomic Predicates

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#132]
Ho riscontrato che il numero di entità presenti nell'ontologia riportati nel widget Info (come da screenshot) è errato. 
O quantomeno non coincide con il numero di Declarations che vengono esportati in OWL (mi sembrava il modo migliore di verificare il numero di entità).

Ad esempio, nell'ontologia in allegato, dice che ci sono 110 Classi, ma nell'OWL ne conto solo 95.
Può essere invece un errore dell'esportazione in OWL? Mi sembra più difficile in effetti, però boh...

In effetti, già che ci siamo, si potrebbero anche aggiungere gli Individuals al conteggio, e invece di usare la dicitura "Atomic Predicates" si potrebbe utilizzare "Entities", che mi sembra più affine ad OWL.

![Schermata 2021-01-27 alle 19 14 09](https://user-images.githubusercontent.com/8250758/106034979-dc943b00-60d3-11eb-9115-d1987c0f1f8c.png)

[ISTAT-SIR.graphol.zip](https://github.com/obdasystems/eddy/files/5882200/ISTAT-SIR.graphol.zip)

[ISTAT-SIR.owl.zip](https://github.com/obdasystems/eddy/files/5882198/ISTAT-SIR.owl.zip)

**Comment by NonnonePalmiro** [comment]
Quello è il project info, e riporta il conteggio dei nodi disegnati come classi e properties, non delle entità nell'ontologia (se conti i nodi classe nel diagramma Vincoli ne trovi 15, che dà proprio la differenza con le 95 declaration nell'owl).  Quindi se una classe viene disegnata due volte viene conteggiata due volte (mi rendo conto naturalmente che le label dell'interfaccia creino un po' di confusione ma sono identiche a quelle che erano presenti già nella versione 1.2).

**Comment by valeriosantarelli** [comment]
Ah ok. Secondo me sarebbe più utile riportare effettivamente il numero di entità (quindi non conteggiando i doppioni ad esempio), ma se per qualche motivo è complicato, forse si potrebbe usare la dicitura Entity Nodes piuttosto che Atomic Predicates.

**Comment by valeriosantarelli** [comment]
Comunque credo che è dall'inizio dell'esistenza di Eddy che sto interpretando male quei numeri... :)

**Comment by NonnonePalmiro** [comment]
Conteggiare le entità non è che sia difficile, ma bisognerebbe fare alcune modifiche a causa dell'inserimento del meta perchè non basta più guardare solo il tipo del nodo ma anche gli assiomi che lo coinvolgono. Naturalmente non è niente che non si possa implementare, quindi intanto cambio l'etichetta e chiudo questo ticket, poi in caso si voglia fare la modifica del conteggio magari apriamo un ticket dedicato per l'enhancement
