### ISSUE TITLE
Gestione errori nell'importazione di ontologie

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#134]
[Errore emerso in ambito ISTAT]

Al momento Eddy adotta un comportamento piuttosto "rigido" nella gestione delle importazioni di ontologie.
In pratica, in caso di qualsiasi errore durante l'esecuzione del processo di informazione, si blocca il processo stesso e viene restituito un errore.

Questo avviene anche, ad esempio, se una delle ontologie importate nell'ontologia che si sta importando (scusate il gioco di parole, ma non so come altro dirlo) non sia parsabile oppure contenga errori.
Questo comportamento differisce da quanto fa Protégé ad esempio, il quale se trova un errore in una delle ontologie importate va comunque avanti.

Per verificare questo comportamento, si può provare ad importare l'ontologia http://www.w3.org/ns/dcat#

L'importazione di questa ontologia produce un errore in Eddy, mentre va a (relativamente) buon fine in Protégé, seppur con il seguente messaggio di errore nel log:
Level:       INFO
Time:        1614351666736
Message:     Failed to load imported ontology at http://purl.org/dc/terms/

Secondo me sarebbe opportuno provare a replicare il comportamento di Protégé in questo caso, e gestire eventuali errori delle ontologie importate.

**Comment by NonnonePalmiro** [comment]
Che versione delle OWL API usa la tua installazione di protégé?  Te lo chiedo perchè purtroppo mi sa che è una cosa gestita internamente dalla libreria Java (noi ora usiamo la stessa versione che usa Mastro ma è parecchio vecchia...)

**Comment by valeriosantarelli** [comment]
Da quello che leggo qui: http://protege-project.136.n4.nabble.com/Protege-5-2-0-Released-td4667857.html è la 4.2.8

**Comment by NonnonePalmiro** [comment]
Noi usiamo la 4.2.6 quindi in realtà è vecchia pure la loro.... Appena possibile do un'occhiata

**Comment by NonnonePalmiro** [comment]
Bisogna utilizzare metodo 
loadOntologyFromOntologyDocument(OWLOntologyDocumentSource documentSource, OWLOntologyLoaderConfiguration config) dopo aver creato opportuna istanza di OWLOntologyLoaderConfiguration con MissingImportHandlingStrategy.SILENT. 
Inoltre bisogna implementare interfaccia Java MissingImportListener per raccolta eccezioni.
