### ISSUE TITLE
Switch domain/range su attributi

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#136]
(Segnalazione di ISTAT)

Ora sugli attributi c'è una leggere discrepanza tra quello che succede sui domini e quello che succede sui range, nel senso che sul dominio è possibile fare lo switch e farlo diventare range, mentre sul range non è possibile farlo.

Due soluzioni:
- o inibiamo a che sul dominio (per le stesse motivazioni che ci fanno non permettere di fare Invert role su un attributo)
- oppure permettiamo di farlo da tutt'e due le parti, però stando attenti che facendolo, non si verifichino errori nell'ontologia a causa di classi/datatypes già agganciati

La prima mi pare molto più semplice, se si sceglie quella per me va benissimo.

**Comment by mnamici** [comment]
In effetti il comportamento attuale non è molto coerente, ad esempio si può fare switch del dominio a range anche se ci sono ISA  da concetti agganciate, e questo chiaramente è un bug a se. 
La prima soluzione ovviamente è piuttosto semplice, mentre per la seconda sto valutando ora ma in realtà non mi sembra complicata neanche quella. In sostanza mi sembra che il comportamento dovrebbe essere il seguente:
 * [Range -> Domain]: si può attivare lo switch a dominio solo se non ci sono domini di valori in ISA. Questo mi sembra sia sufficiente a coprire tutti i casi, permettendo lo switch quando è presente un attributo fintanto che non si definisce una ISA con valori, mentre per il ruolo viene sempre permesso. Il resto delle condizioni sono gestite dalle altre regole, as esempio non si può agganciare un ruolo in input ad un range restriction in ISA con un valore).
 * [Domain -> Range]: si può attivare lo switch a range sempre ad eccezione del caso in cui ci sia un attributo in input ed una espressione di classe in ISA (in qualsiasi direzione). Questo permetterebbe appunto lo switch domain -> range per una range restriction collegata ad un attributo fintanto che non si mette in ISA qualcosa con il nodo restrizione di dominio. Come sopra le restanti casistiche sono coperte da altre regole sintattiche (ad esempio non si può agganciare in input un attributo ad una range restriction in ISA con una classe).

Che ne pensate? Vi sembra abbia dimenticato qualcosa? Se vi sembra corretto la modifica in realtà l'ho già prototipata per fare le prove e mi sembra si comporti correttamente quindi potrei committarla.

**Comment by valeriosantarelli** [comment]
Si, mi pare il comportamento corretto, se è di semplice implementazione per me si può procedere.

**Comment by mnamici** [comment]
Perfetto, i nuovi build sono già disponibili su bintray se gli volete dare un'occhiata.
