### ISSUE TITLE
Errore durante cancellazione di una entità

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#148]
La cancellazione di una entità per la quale è definita una annotazione contenente un carattere accentato genera il seguente errore:

```
Traceback (most recent call last):
  File "eddy/ui/session.py", line 1886, in doDelete
  File "eddy/ui/session.py", line 1815, in common_commands_for_cut_delete_purge
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 65: ordinal not in range(128)
```

Per verificare, si può provare a cancellare l'attributo `data_inizio_validita_indirizzo` da questa ontologia: 
[ISTAT-SIR_v1.1.25.graphol.txt](https://github.com/obdasystems/eddy/files/7098857/ISTAT-SIR_v1.1.25.graphol.txt)

**Comment by valeriosantarelli** [comment]
Aggiungo che se si cancella l'annotazione, l'eliminazione dell'entità va a buon fine.

**Comment by mnamici** [comment]
Credo sia un problema legato al rendering per rdfs:label, anche se non riesco a riprodurlo ne con la versione 3.1 ne sul branch di sviluppo con il file caricato. Puoi verificare se scaricandolo riesci a riprodurlo tu stesso? In caso la causa del problema potrebbe scomparire quando si salva il progetto quindi bisogna indagare.
Ad ogni modo quel metodo non esiste più sul branch di sviluppo, se puoi controlla se ancora si presenta il problema con l'ultimo build. Lo puoi scaricare da [qui](https://github.com/obdasystems/eddy/actions/runs/1193552689).

**Comment by valeriosantarelli** [comment]
Confermo, non si ripresenta. Chiudo allora.
