### ISSUE TITLE
Annotations esportate

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#155]
Al momento Eddy esporta sempre e comunque tutte le annotations, anche quelle relative a entità presenti in diagrammi che non si vogliono esportare.

Esempio: ho due diagrammi, scelgo di esportare in OWL solo uno di essi, nell'OWL comunque avrò le annotations di tutte le entità dei due diagrammi.

**Comment by mnamici** [comment]
Confermo, riproducibile su 3.1 e su develop.
