### ISSUE TITLE
Export Graphol ontology

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#16]
Dovrebbe essere permesso esportare in formato graphol uno o più dei diagrammi che formano l'ontologia.

**Comment by NonnonePalmiro** [comment]
Tutte le caratteristiche del progetto (IRI dell'ontologia, prefissi, lingue, etc....) dovranno essere ereditate dal sottoprogetto esportato, o bisognerà prevedere una interfaccia da cui configurare le nuove proprietà ?

**Comment by valeriosantarelli** [comment]
No, io per il momento lascerei tutti i metadati del progetto esattamente così come sono.
Non sono mai emerse esigenze particolari da questo punto di vista.

**Comment by NonnonePalmiro** [comment]
La funzionalità è stata aggiunta alla versione per MacOS su Drive

**Comment by valeriosantarelli** [comment]
Confermo e chiudo.
