### ISSUE TITLE
Installazione di plugin blocca l'intera applicazione

### ISSUE THREAD

**Issue by danielepantaleone** [obdasystems/eddy#176]
Ciao, 

Ho notato che quando si apre la schermata di installazione di un plugin non si può uscire (su macOS almeno) a meno che non venga selezionato il file del plugin da installare (probabilmente una cosa molto vecchia che non ho gestito io al tempo). Bisogna killare l'app dal terminale oppure effettuare un force quit da UI.

<img width="1440" alt="Screenshot 2022-01-20 at 10 00 37" src="https://user-images.githubusercontent.com/1245124/150306995-a626b80d-989f-4f21-a9d5-da2deab20fe1.png">

**Comment by mnamici** [comment]
Ciao Daniele,

credo che il problema sia dovuto al fatto che a partire da macOS 11 le finestre di dialogo (le istanze di QDialog per capirci) vengano mostrate di default senza frame, quindi l'unico modo rimasto per cancellare l'operazione è premere il tasto ESC. Puoi verificare se premendolo sia possibile uscire dalla finestra di dialogo modale?

Ad ogni  modo sicuramente ci vuole un pulsante per annullare l'operazione di installazione che ho aggiunto in #178.
