### ISSUE TITLE
[Font] problema visualizzazione di elementi font non di default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#185]
Se apro l'ontologia in allegato con una versione di Eddy successiva alla 3.1 (ovvero dalla 3.2 in poi) alcuni elementi del diagramma non vengono visualizzati.
La mia impressione è che questi ultimi siano quelli per cui è stato modificato il font da quello di default a uno custom.

[Interstat.graphol.zip](https://github.com/obdasystems/eddy/files/8284366/Interstat.graphol.zip)

Questo è quello che si vede con Eddy v3.2:
![Schermata 2022-03-17 alle 12 41 40](https://user-images.githubusercontent.com/8250758/158801328-3ca994e3-a597-4104-a04a-8b5e66c76f52.png)

Questo invece è quello che si vede con Eddy 3.1:
![Schermata 2022-03-17 alle 12 44 35](https://user-images.githubusercontent.com/8250758/158801744-dca34b32-bb24-4c2c-ac35-4b3fc79eed14.png)

**Comment by mnamici** [comment]
> La mia impressione è che questi ultimi siano quelli per cui è stato modificato il font da quello di default a uno custom.

In effetti sono proprio gli item con i font cambiati, ad ogni modo il fix è veramente semplice. Aggiunto ai fix per la 3.2.1
