### ISSUE TITLE
Existential Restriction

### ISSUE THREAD

**Issue by RichDijk** [obdasystems/eddy#189]
Hello,

Thank you for developing Eddy. How do I model a Existential Restriction like

```
vph-g:CaseRole rdf:type owl:Class ;
               rdfs:subClassOf vph-g:Participant ,
                               [ rdf:type owl:Restriction ;
                                 owl:onProperty vph-g:isCaseRoleParticipantIn ;
                                 owl:someValuesFrom vph-g:Perdurant
                               ] ;
```

**Comment by RichDijk** [comment]
The essential restriction is clear now. 
![afbeelding](https://user-images.githubusercontent.com/11976070/162632878-1436a0b3-a907-4449-8117-25af6144bd8a.png)

The Universal restriction remains unclear to me
```
vph-g:CorpuscularObject rdf:type owl:Class ;
                        rdfs:subClassOf vph-g:PhysicalObject ,
                                        [ rdf:type owl:Restriction ;
                                          owl:onProperty vph-g:hasObjectLocation ;
                                          owl:allValuesFrom vph-g:CorpuscularObject
                                        ] ;

```

**Comment by mnamici** [comment]
Hello,

Thank you for using Eddy. The Graphol structure for universal restriction is the same as the existential restriction, with the difference that you have to set the domain restriction node (the white square) to a universal restriction by right-click the node -> switch restriction -> universal. 
If you haven't already, I suggest you have a look at the project [wiki](https://github.com/obdasystems/eddy/wiki) where you can find a short introduction to Graphol and it's use in Eddy. There is also a [Graphol syntax](https://github.com/obdasystems/eddy/wiki/documentation/GrapholSyntax.pdf) reference which shows some of the common expressions and their corresponding structure in Graphol.

**Comment by RichDijk** [comment]
Thank you that works nicely.
