### ISSUE TITLE
[FEATURE] Tooltip per pulsanti del importazione

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#207]
Al momento i pulsanti nel menu relativi all'importazione, ovvero quelli nello screenshot sotto, non sono provvisti di tooltip che indica cosa fa il pulsante quando si va in hover con il mouse.
Sarebbe utile aggiungerlo, visto che non ci sono altri modi di azionare le stesse operazioni, e non ci sono altre indicazioni su cosa fanno quei pulsanti. 
![Schermata 2022-06-16 alle 18 12 49](https://user-images.githubusercontent.com/8250758/174117265-e025754d-2a46-495f-bea6-dd35ad983754.png)

**Comment by MariaRosariaFraraccio** [comment]
Aggiunto
