### ISSUE TITLE
Edge Descriptions

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#21]
Add support for descriptions on inclusion edges.

The description panel should be the same as the one for ontology predicates.

**Comment by valeriosantarelli** [comment]
Questo in pratica si traduce nella possibilità di definire una annotation per un arco (quindi su un assioma, come avviene in Protégé).

**Comment by valeriosantarelli** [comment]
Ieri in una call con Almawave con @giacomoronconiobda è emersa una discussione riguardo a questo tema.
In effetti potrebbe essere utile, soprattutto come criterio per distinguere le gerarchie, in caso una classe ne abbia più di una.

Non è ovviamente una richiesta di intervento immediato (anche perchè coinvolge anche il parser di mastro e Grapholscape), però almeno abbiamo evidenza che è una buona idea, quindi potrebbe avere maggiore priorità rispetto alle altre issue che al momento sono idee nostre senza riscontri esterni.

**Comment by NonnonePalmiro** [comment]
Ma si tratta di Annotation sugli assiomi (cioè solo sugli archi che inducono assiomi) o di commenti generali su un qualunque arco?

**Comment by valeriosantarelli** [comment]
Per come me la stavo immaginando io, di Annotations sugli assiomi, nella modalità prevista da OWL.

Commenti generali su qualunque arco credo rientrino nella categoria di "commenti generali sui diagrammi", che per il momento non supportiamo (poi possiamo pensare anche di farlo se troviamo una soluzione efficace).
