### ISSUE TITLE
[BUG]: Gestire eccezioni parser OWL API

### ISSUE THREAD

**Issue by MariaRosariaFraraccio** [obdasystems/eddy#210]
### Describe the bug

Alcuni assiomi (in formato stringa) non possono essere automaticamente resi in formato Axiom dal parser di OWL API e quindi disegnati nel diagramma.

### Reproduction Steps

Dopo aver importato un'ontologia nel progetto, selezionare un assioma da disegnare dall'elenco di assiomi dell'ontologia.

### Affected Versions

3.3.dev0

### Operating System

GNU/Linux

### Operating System Version

Ubuntu 20.10

### Operating System Architecture

x86_64

**Comment by MariaRosariaFraraccio** [comment]
![Schermata da 2022-07-08 18-27-53](https://user-images.githubusercontent.com/45686128/178032819-d1647f23-7ff6-47f9-a6c6-a259ac161b3e.png)

**Comment by mnamici** [comment]
Il messaggio in questione viene generato nella classe OWLAPI `impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLOntologyManagerImpl.java:1306` tramite LOGGER.warn nel metodo `fixIllegalPunning(OWLOntology o)`, quindi non è un'eccezione. 
Presumo che nel nostro caso invece riceviamo un'eccezione da OWLAPI, corretto? Viene attualmente generata una traccia delle eccezioni ricevute nel system log dal plugin? Per capire come procedere se decidiamo di proseguire lo stesso con questo tipo di situazione.

**Comment by mnamici** [comment]
Allora ho indagato un pò ed il motivo per cui non riusciamo a parsare di nuovo gli assiomi è legato al fatto che usiamo la sintassi manchester per la serializzazione. Per riprodurre il problema anche dentro protégé basta seguire i seguenti step:
1) importare l'ontologia ANAC in protégé
2) fare `Save As...`, selezionare sintassi manchester
3) provare ad aprire il nuovo file salvato in sintassi manchester.

Il problema di fatto è il seguente: la sintassi manchester è ambigua rispetto a questi casi di punning illegali secondo la specifica OWL 2. Il motivo per cui invece riusciamo a parsare inizialmente l'ontologia è perché questa è espressa in sintassi funzionale nel file owl. Per esempio nel nostro caso durante la prima importazione dell'ontologia dal file abbiamo l'assioma:
```
EquivalentClasses(VariantReason DataSomeValuesFrom(hasVariantReason rdfs:Literal))
```
in questo caso non c'è ambiguità, perche il costrutto `DataSomeValuesFrom` chiaramente proietta la prima componente di una DataProperty, e quindi il parser funzionale sa cosa deve fare. Nel momento il cui l'assioma viene serializzato nel db però si ottiene il seguente assioma secondo la sintassi manchester:
```
VariantReason EquivalentTo hasVariantReason some Literal
```
in questo secondo caso non c'è modo di capire dal costrutto `some` se stiamo parlando di una ObjectProperty o DataProperty (ed inoltre è una situazione non tecnicamente permessa da OWL 2), quindi il parser manchester prova una alla volta i tipi di entità, nel seguente modo:
```java
    public OWLAxiom parseAxiom() {
        String token = peekToken();
        if (isClassName(token)) {
            return parseAxiomWithClassExpressionStart();
        } else if (isObjectPropertyName(token)) {
            return parseAxiomWithObjectPropertyStart();
        } else if (isDataPropertyName(token)) {
            return parseAxiomWithDataPropertyStart();
        } else if (isIndividualName(token)) {
            return parseAxiomWithIndividualStart();
        } else if (INV.matches(token)) {
            return parseAxiomWithObjectPropertyStart();
        } else if (OPEN.matches(token)) {
            return parseAxiomWithClassExpressionStart();
        } else if (OPENBRACE.matches(token)) {
            return parseAxiomWithClassExpressionStart();
        } else if (FUNCTIONAL.matches(token)) {
            return parseFunctionPropertyAxiom();
        } else if (INVERSE_FUNCTIONAL.matches(token)) {
            return parseInverseFunctionalPropertyAxiom();
        } else if (SYMMETRIC.matches(token)) {
            return parseSymmetricPropertyAxiom();
        } else if (ASYMMETRIC.matches(token)) {
            return parseAsymmetricPropertyAxiom();
        } else if (TRANSITIVE.matches(token)) {
            return parseTransitivePropertyAxiom();
        } else if (REFLEXIVE.matches(token)) {
            return parseReflexivePropertyAxiom();
        } else if (IRREFLEXIVE.matches(token)) {
            return parseIrreflexivePropertyAxiom();
        }
        throw new ExceptionBuilder()
            .withClass().withObject().withData().withKeyword(OPEN, OPENBRACE, INV, FUNCTIONAL,
                INVERSE_FUNCTIONAL, SYMMETRIC, ASYMMETRIC, TRANSITIVE, REFLEXIVE, IRREFLEXIVE)
            .build();
```
poiché il test `isObjectPropertyName(hasVariantReason)` restituisce `true` in quanto è sia Object che Data Property, il resto fallisce in quanto non è ammesso un tipo di dato come filler dell'espressione.
Nota che la stessa ambiguità c'è anche con altre sintassi (ad esempio rdf/xml e turtle), ed anche con altri tipi di assiomi ed il punning tra properties, (vedi ad esempio la funzionalità, di cui ci eravamo accorti qualche tempo fa). L'unica sintassi a non presentare questo tipo di ambiguità è quella funzionale.

La soluzione è usare sempre la sintassi funzionale per la serializzazione. Nota bene che questo non implica che dobbiamo per forza usarla per il rendering, ma possiamo ancora presentare gli assiomi con la sintassi che vogliamo usando il renderer appropriato, magari salvandole comunque nel db per motivi di efficienza.

**Comment by MariaRosariaFraraccio** [comment]
Problema risolto: manteniamo nel db anche l'assioma in sintassi funzionale. La prima serializzazione che proviamo è sulla sintassi funzionale, essendo la meno ambigua, e nei rari casi in cui questa non va a buon fine continuiamo con la serializzazione sulla sintassi manchester.
