### ISSUE TITLE
[BUG]: Assiomi non presenti per importazione

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#212]
### Describe the bug

Dopo aver importato una ontologia, e disegnato la gerarchia delle classi, non risultano gli altri assiomi da importare.

![Schermata 2022-07-15 alle 09 13 34](https://user-images.githubusercontent.com/8250758/179171852-a78c9172-d39f-4a39-906f-5800550f12dc.png)

### Reproduction Steps

Per replicare si può usare questa ontologia:

[ontology-v1.0.0-snapshot.owl.zip](https://github.com/obdasystems/eddy/files/9118749/ontology-v1.0.0-snapshot.owl.zip)

### Affected Versions

3.3dev0

### Operating System

macOS

### Operating System Version

macOC 12.4

### Operating System Architecture

x86_64

**Comment by mnamici** [comment]
Chiudo in quanto risultante da modifiche nel db, a partire #214 sono versionate quindi se ci sono modifiche se ne tiene traccia e viene verificato all'avvio.
