### ISSUE TITLE
[BUG]: Inserimento assiomi con stessa forma in Manchester syntax in db durante importazione

### ISSUE THREAD

**Issue by MariaRosariaFraraccio** [obdasystems/eddy#240]
### Describe the bug

Durante il processo di importazione di un'ontologia, nel caso in cui due assiomi differenti abbiano la stessa forma in sintassi Manchester, uno solo di questi viene inserito nel db a causa della primary key degli assiomi costituita proprio dall'assioma in sintassi Manchester, l'IRI e la versione dell'ontologia.

### Reproduction Steps

Importare un'ontologia contenente ad esempio i seguenti assiomi:
`ClassAssertion(<http://www.w3.org/2006/vcard/ns#Organization> <https://w3id.org/italia/data/contact-point/onto-agid>)
`

`ClassAssertion(<http://dati.gov.it/onto/dcatapit#Organization> <https://w3id.org/italia/data/contact-point/onto-agid>)`

### Actual Result

Uno solo dei due assiomi è presente nell'elenco e quindi uno solo dei due può essere disegnato.

![Schermata del 2022-11-21 12-23-29](https://user-images.githubusercontent.com/45686128/203038686-244bc1f3-b349-4e91-8609-f9c97707e047.png)

### Affected Versions

3.3

### Installation

GNU/Linux AppImage

### Operating System

GNU/Linux

### Operating System Version

Ubuntu 22.04 LTS

### Operating System Architecture

x86_64

**Comment by mnamici** [comment]
Riassumo brevemente qui quello che ci siamo detti durante il meeting:

Il problema è dato dal fatto che in fase di serializzazione degli assiomi si una una INSERT OR IGNORE nella tabella `axiom` che ha come parte della chiave la forma Manchester dell'assioma, quindi in caso di ambiguità l'inserimento non avviene (viene ignorato) a causa della risultante violazione della chiave primaria, anche se la forma funzionale ci permetterebbe di risolvere tale ambiguità. 

La soluzione che conviene adottare è quella in cui ovunque si usi la rappresentazione sintattica dell'assioma come (parte di) chiave si usi la sintassi funzionale, relegando la memorizzazione della sintassi manchester a semplice comodità.

Le modifiche da fare per la prossima release sono le seguenti:
1) Modificare lo schema SQL, sostituendo l'attributo `axiom.func_axiom` con `axiom.manch_axiom` (o nome simile), e facendo si che l'attributo `axiom.axiom` contenga la versione funzionale dell'assioma invece della manchester.
2) Implementare una prima versione del meccanismo di migrazione di versione del db. Dal punto di vista logico il meccanismo dovrebbe avere una struttura del genere:
Durante la `checkDatabase()`, confrontare la versione attuale db con quella del plugin; Se tale versione risulta inferiore, eseguire _sequenzialmente_ una serie di step consistenti in una lista di comandi SQL memorizzati in una struttura dati con la seguente struttura:
```python
upgrade_commands = {
    1: [ 'lista comandi per passare da versione 1 a 2' ],
    2: [ 'lista comandi sql per passare da versione 2 a 3' ],
    3: [ 'lista comandi sql per passare da versione 3 a 4' ]
    # ecc... fino alla versione attuale del db
}
```
Qualora la versione del db su disco (la `PRAGMA user_version`, vedi #203 per dettagli) risulti minore della versione implementata dal plugin (che è nello spec file), applicare uno ad uno gli step di upgrade nel seguente modo:
```python
while pragma user_version != plugin_version:
    execute upgrade_commands[pragma user_version]
    pragma user_version = pragma user_version + 1
```

ad esempio, per questa migrazione (da versione 1 a 2), la sequenza di comandi dovrebbe essere all'incirca la seguente (verifica, non ho testato):
```sql
BEGIN TRANSACTION;

-- Rimpiazza drawn.axiom con la versione funzionale
UPDATE drawn SET axiom = q.func_axiom
FROM (
    SELECT 
        d.project_iri, 
        d.ontology_iri, 
        d.ontology_version, 
        d.axiom, 
        a.func_axiom 
    FROM 
        axiom a, 
        drawn d 
    WHERE a.axiom = d.axiom 
      AND a.ontology_iri = d.ontology_iri 
      AND a.ontology_version = d.ontology_version
) AS q
WHERE drawn.project_iri = q.project_iri
  AND drawn.ontology_iri = q.ontology_iri
  AND drawn.ontology_version = q.ontology_version
  AND drawn.axiom = q.axiom

-- Scambia axiom con func_axiom nella tabella axiom
UPDATE axiom SET axiom = func_axiom, func_axiom = axiom;

-- Rinomina func_axiom
ALTER TABLE axiom RENAME COLUMN func_axiom TO manch_axiom;

COMMIT;
```
3) Rivedere tutti gli accessi al database nel codice del plugin, tenendo in considerazione che ora l'attributo `axiom` contiene la versione funzionale, e l'attributo `func_axiom` non c'è più ed è stato rinominato.
