### ISSUE TITLE
[FEATURE]: Inibire l'uso dell'apostrofo nelle IRI

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#244]
### Description

Come da oggetto: a meno di non fare in automatico qualche operazione di escape, sarebbe meglio proibire l'uso del carattere apostrofo in tutte le IRI.

### Motivation

Strumenti quali Protègè restituiscono um errore di parsing se trovano l'apostrofo in un a IRI dell'ontologia.

### Example Use Cases

[INPS_23112022 (1).owl.zip](https://github.com/obdasystems/eddy/files/10156274/INPS_23112022.1.owl.zip)

Allego esempio di OWL prodotto da Eddy che restituisce l'errore.

**Comment by mnamici** [comment]
Riporto per promemoria quanto discusso durante il meeting: 

Il problema riscontrato è dovuto alla seguente IRI nell'ontologia allegata:
`http://dati.inps.it/sinpson/importo_medio_mensile_dell’integrazione_al_minimo`

Da notare che l'apostrofo presente non è il tipico `'` (unicode U+0027, ASCII 27) ma il carattere unicode `’`, (U+2019). 

Questa IRI è perfettamente valida secondo la specifica rfc 3987 (le IRI appunto), quindi il problema non è legato alla IRI di per se, ma al fatto che nell'ontologia esportata (in sintassi turtle) viene riportata nella versione prefissata:
`sinpson:importo_medio_mensile_dell’integrazione_al_minimo` 
e quest'ultima non riesce ad essere parsata da OWLAPI, che invece non ha problemi se la IRI viene espressa in formato esteso:
`<http://dati.inps.it/sinpson/importo_medio_mensile_dell’integrazione_al_minimo>`

Questa discrepanza suggerirebbe che la forma prefissata non ammette gli stessi caratteri della forma estesa, il che mi risulta difficile da credere, quindi sospetto si tratti di una limitazione di OWLAPI sulla gestione delle IRI prefissate, cosa che però va verificata (anche rispetto a versioni più recenti).
