### ISSUE TITLE
Distinguere entità deprecate

### ISSUE THREAD

**Issue by MariaRosariaFraraccio** [obdasystems/eddy#260]
Distinguere la rappresentazione dei nodi associati ad entità che hanno l'annotazione `owl:deprecated` con valore `true`.

**Comment by mnamici** [comment]
Aggiungo la label graphol perché non è chiaro se questa modifica richieda combiamenti al formato graphol.

**Comment by mnamici** [comment]
Per riferimento riporto quello che ho trovato nella specifica del vocabolario [OWL](http://www.w3.org/2002/07/owl) relativamente all'annotazione `owl:deprecated`, la quale è descritta nel seguente modo:

```rdf
owl:deprecated a owl:AnnotationProperty ;
     rdfs:label "deprecated" ;
     rdfs:comment "The annotation property that indicates that a given entity has been deprecated." ;
     rdfs:domain rdfs:Resource ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> ;
     rdfs:range rdfs:Resource . 
```

Mentre la [structural specification](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#a_deprecated) riporta la seguente frase:
> An annotation with the owl:deprecated annotation property and the value equal to "true"^^xsd:boolean can be used to specify that an IRI is deprecated. 

Lasciando libera interpretazione all'applicazione di cosa il fatto di essere deprecato significhi, quindi un semplice metadato.

Questo ci conferma che la strategia migliore per gestirla è esattamente quella che abbiamo descritto durante la call, ovvero:
- Non restringere il tipo di valore che si può specificare per `owl:deprecated`.
- Aggiungere un'azione contestuale ai nodi entità che si comporta nel seguente modo:
  - Se la IRI corrispondente ha una annotazione `owl:deprecated` E tale annotazione ha valore `"true"^^xsd:boolean` mostra magari una spunta, e se cliccata la rimuove.
  - In caso contrario non mostra la spunta e se cliccata la inserisce.
- Gestire la presenza di tali annotazioni nell'ontology explorer, mostrando il nome ad esempio sbarrato.
