### ISSUE TITLE
[BUG]: creazione ontologia da file OWL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#270]
### Describe the bug

Scegliendo la modalità di creazione di una ontologia da file OWL, Eddy restituisce un errore.

### Reproduction Steps

Allego l'ontologia che genera l'errore.

[GPTdocu.owl.zip](https://github.com/obdasystems/eddy/files/12925972/GPTdocu.owl.zip)

### Actual Result

Stacktrace dell'errore:

```
Traceback (most recent call last):
  File "Absent.java", line 47, in com.google.common.base.Absent.get
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/eddy/eddy/eddy/plugins/ontology-importer/ontology_importer.py", line 1158, in doOpenOntologyFile
  File "/Users/runner/work/eddy/eddy/eddy/plugins/ontology-importer/ontology_importer.py", line 1010, in doOpenOntologyFile
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
```

### Affected Versions

3.5, 3.5.1

### Installation

macOS `dmg`

### Operating System

Windows

### Operating System Version

macOC 12.6

### Operating System Architecture

x86_64

**Comment by MariaRosariaFraraccio** [comment]
Va in errore perché nel file non c'è l'IRI dell'ontologia, non so se vogliamo permetterlo

**Comment by valeriosantarelli** [comment]
Idealmente direi di no, però per evitare situazioni di errore che poi ci tocca gestire, potremmo anche pensare che se c'è modo di generarne una (in stile protege per intenderci), lo facciamo.

Altrimenti comunque cerchiamo di lanciare un messaggio di errore parlante.

**Comment by mnamici** [comment]
Ho messo una proposta di fix nella PR allegata, al momento uso la URI del file contenente l'ontologia per permettere al db di identificarla. Fatemi sapere che ne pensate.
