### ISSUE TITLE
[BUG]: Start Eddy on W11

### ISSUE THREAD

**Issue by bruno-marino** [obdasystems/eddy#275]
### Describe the bug

Unable to start Eddy on Windows 11.

![image](https://github.com/obdasystems/eddy/assets/48441496/123c8eb4-426e-4480-bd11-758e1aea12bd)

![image](https://github.com/obdasystems/eddy/assets/48441496/0351c004-2108-4edc-8a06-75a993996b8a)

### Reproduction Steps

Install Eddy with the .exe installer or zip file.

### Expected Result

Eddy started.

### Actual Result

Eddy not start.

### Affected Versions

3.5.1,3.5.0

### Installation

Windows Installer

### Operating System

Windows

### Operating System Version

Windows 11

### Operating System Architecture

x86_64

### Log

```sh
Traceback (most recent call last):
  File "run.py", line 43, in <module>
  File "eddy\core\application.py", line 636, in main
  File "eddy\core\application.py", line 251, in configure
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10
```

**Comment by mnamici** [comment]
Looks like a null value has been saved in the list of recent projects, however I'm not able to reproduce this locally on a fresh install of Windows 11 so it is difficult to say what can cause it.

Does the issue happen again if you select `Close` on the exception dialog, open any project, and then close and reopen Eddy?

**Comment by mnamici** [comment]
Yes, you can delete the list of recent projects on Windows by editing the registry (`Win+R`, then execute `regedit`).
Then, delete the following key:
```
HKEY_CURRENT_USER\SOFTWARE\Eddy\Eddy\project\recent
```
It will be recreated when you start Eddy again.
Let me know if this fixes the issue on your side.

**Comment by bruno-marino** [comment]
> Yes, you can delete the list of recent projects on Windows by editing the registry (`Win+R`, then execute `regedit`). Then, delete the following key:
> 
> ```
> HKEY_CURRENT_USER\SOFTWARE\Eddy\Eddy\project\recent
> ```
> 
> It will be recreated when you start Eddy again. Let me know if this fixes the issue on your side.

The proposed solution fix the problem.
Thanks!

**Comment by mnamici** [comment]
Ok thanks. Glad to hear that fixes it.
