### ISSUE TITLE
[FEATURE]: Creazione progetto da ontologia con estensione diversa da OWL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#281]
### Description

Come da oggetto: attualmente è possibile selezionare solo file con estensione .owl

File .rdf contenenti ontologie in OWL sono ad esempio ignorati.

### Motivation

Al momento se si ha una ontologia in rdf o altre estensioni di OWL, bisogna modificare l'estensione del file oppure salvarla con altro nome tramite Protege, e poi caricarla.

### Example Use Cases

![Screenshot 2024-05-21 alle 23 36 09](https://github.com/obdasystems/eddy/assets/8250758/034a5afc-56c6-47d5-8d59-702e0f91792f)

**Comment by mnamici** [comment]
Il filtro `OWL Ontology Languge` restringe la visualizzazione a file con estensioni owl tra quelle suggerite nello standard, in particolare: 

* `*.owl`: Comunemente usata ma non parte dello standard
* `*.ofn`: Per la sintassi funzionale
* `*.owx`: Per la sintassi RDF/XML
* `.omn`: Per la sintassi Manchester
* `*.ttl`: Per turtle

Ho messo la possibilità di aprire qualsiasi file cambiando il filtro a `All Files`. Questo dovrebbe coprire tutti gli scenari attuali e futuri (anche se non c'è l'estensione per esempio).
