### ISSUE TITLE
[BUG]: Link for "Graphol" in README.md is dead

### ISSUE THREAD

**Issue by tillmo** [obdasystems/eddy#283]
### Describe the bug

The link for "Graphol" in README.md is dead

### Reproduction Steps

Click on the link "Graphol" leading to http://www.diag.uniroma1.it/~graphol

### Expected Result

The link should lead to an existing page.

### Actual Result

404

### Affected Versions

develop

### Installation

None

### Operating System

GNU/Linux

### Operating System Version

Ubuntu 20.04

### Operating System Architecture

x86_64

**Comment by mnamici** [comment]
Thanks for noticing, looks like the old web server from our department has been dismissed and we don't have a proper replacement for now.
