### ISSUE TITLE
Entity name modified when serializing  owl ontology document

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/eddy#33]
Se nell'ontologia specificata nel Graphol compare un nome di entità contenente il carattere '-', quest'ultimo viene trasformato nel carattere '_' senza che l'utente ne abbia contezza. 

Se è il serializzatore delle owl api ad applicare tale trasformazione si suggerisce di impedire l'utilizzo del carattere '-' per la definizione delle IRI. 

A titolo di esempio si consideri il concetto ':E-Book' definito nell'ontologia Books

**Comment by mnamici** [comment]
La trasformazione non avviene all'interno delle owl api ma nell'esportatore OWL, durante la fase di generazione delle IRI a partire dai label dei nodi. In sostanza l'esportatore costruisce una IRI composta dal prefisso del nodo e dalla parte rimanente dove vengono sostituiti tutti i caratteri non alfanumerici con degli '_'. Questa restrizione è errata in quanto sono ammessi alcuni caratteri non alfanumerici (come '-') nei segmenti delle IRI.

In 76068f9f ho esteso i caratteri ammessi nella parte seguente al prefisso secondo la regola di produzione `iunreserved` nella grammatica descritta in [RFC 3987](https://www.ietf.org/rfc/rfc3987.txt), questo dovrebbe risovere il problema.
