### ISSUE TITLE
Esportazione ed importazione

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#34]
Ricevo una segnalazione di problemi legati a queste funzionalità in Eddy, relativamente al file in allegato.

Di seguito la segnalazione:

> (1) l’esportazione dei diagrammi funziona molto male, quasi sempre il tentativo di esportazione fa cadere il sistema… per avere qualche speranza bisogna ignorare le opzioni: dare un nome nuovo al file, selezionare i diagrammi, scegliere la directory di esportazione; se lasci a lui la scelta di queste cose probabilmente funziona; inoltre l’esportazione è “sporca” ci sono dati strani che si vedono quando apri il pdf
> 
> (2) l’importazione ha problemi ancora più gravi; a me si è rotto il vecchio computer ma sono riuscito a salvare le ontologie che avevo prodotto (e che sono importanti per me); ma è impossibile aprirle perché Eddy cerca qualcosa (credo) da un’altra parte che non si sa dove sia… sembra che i file delle ontologie siano inutilizzabili (il tentativo di aprirli fa, ancora una volta, cadere il sistema).

Credo che la problematica segnalata in modo più chiaro sia la seconda; per quanto riguarda la prima bisognerebbe vedere un attimo effettivamente cosa succede nel vari passi di importazione.

[Sapientia.graphol.zip](https://github.com/obdasystems/eddy/files/3353686/Sapientia.graphol.zip)

**Comment by mnamici** [comment]
Relativamente alla prima problematica non riesco a riprodurre errori in fase di esportazione pdf o jpeg relativa alla scelta del file/cartella in cui salvare il risultato utilizzando l'ultima release.

Per quanto riguarda i dati "strani" credo si riferisca alle tabelle contenenti le IRI dei predicati, che non vengono scalate correttamente nel pdf generato, ma appaiono molto piccole alla fine del documento
(come si vede di seguito).

![issue34](https://user-images.githubusercontent.com/37672765/60984087-61c1ce80-a33b-11e9-8804-7e447be3357f.png)

 
Questo è un problema già noto, forse possiamo aprire una issue relativa per tenerne traccia.

La seconda problematica sembra invece essere relativa all'importazione della versione 1 di Graphol,
ma è difficile esserne sicuri senza sapere qual'è la versione di Eddy in uso. Se così fosse il problema è già stato risolto in c3e67ed8b9.

**Comment by valeriosantarelli** [comment]
Ho chiesto a Paolo che versione sta usando, appena risponde aggiorno.

**Comment by valeriosantarelli** [comment]
Aggiunta alla issue #18 la parte relativa alle tabelle da scalare correttamente.

**Comment by mnamici** [comment]
Ho risolto il problema relativo alle tabelle dei predicati che non venivano scalate correttamente, ora vengono corretamente scalate su fogli di dimensione A4, ho sistemato anche i diagrammi che avevano dimensioni differenti nel file ed aggiunto il titolo su ogni diagramma. Allego una copia dell'esportazione di ACI Open Data:

[ACIOpenData.pdf](https://github.com/obdasystems/eddy/files/4072340/ACIOpenData.pdf)

Ora però dobbiamo fare una scelta, se vogliamo mantenere tutti i fogli nel pdf della stessa dimensione c'è il problema che i diagrammi molto grandi (come quello delle formalità) vengono rimpiccioliti parecchio e possono risultare difficili da leggere, in alternativa possiamo adottare dimensioni più grandi per i diagrammi come A3, oppure lasciare la dimensione originale, il che può produrre però delle pagine molto grandi. Che ne pensi?

**Comment by valeriosantarelli** [comment]
Sarebbe possibile, con sforzo ragionevole (cioè poco) permettere di scegliere tra A4 e A3?

**Comment by mnamici** [comment]
Si potrebbe fare una finestra di dialogo per la selezione della dimensione utilizzando i formati standard (tra cui A4 ed A3), però a lungo termine sarebbe il caso di eliminare tutte queste finestre di dialogo e creare un wizard di esportazione unico. La selezione la applichiamo solo ai diagrammi mantenendo le tabelle in A4 o ad entrambi? Per me la prima opzione è più sensata.

**Comment by valeriosantarelli** [comment]
Direi la prima.

**Comment by mnamici** [comment]
Il nuovo pannello per la selezione del formato è stato completato in ffc2893. Come stabilito si applica solamente ai diagrammi e non alle pagine con le tabelle dei predicati.
