### ISSUE TITLE
Creazione nuovo progetto

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#40]
Una volta aperto un progetto esistente _P_ non si può creare un nuovo progetto _N_ senza prima chiudere _P_. Aggiungere al menu File una voce `New Project`

**Comment by valeriosantarelli** [comment]
Questa funzionalità è già implementata, anche nella versione 3.0, si fa attraverso la voce "Open" del menu File.

Incollo screenshot per testimonianza.

<img width="1333" alt="Schermata 2020-05-09 alle 08 52 43" src="https://user-images.githubusercontent.com/8250758/81466502-85aba600-91d2-11ea-9838-604f0834b4b2.png">
