### ISSUE TITLE
Creazione di datatype custom

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#41]
Per poter usare le funzione geo spaziali di Mastro bisognerebbe definire il range di un attributo su uno dei tipi di dato di GEOSparql. Questo sarebbe `http://www.opengis.net/ont/geosparql#wktLiteral` che non c'è ora nei datatype che si possono definire. Forse bisognerebbe in generale permettere di creare datatype custom.

**Comment by valeriosantarelli** [comment]
Funzionalità supportata dalla versione 2.0 di Eddy. Chiudo.
