### ISSUE TITLE
Link nel Menu Help

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#43]
Attualmente i link nel Menu help riportano ai siti vecchi.

Bisogna modificarli, indicando:

- Visit OBDA Systems website -> www.obdasystems.com
- Visit Eddy website -> www.obdasystems.com/Eddy
- Visit Graphol website -> www.obdasystems.com/Graphol

**Comment by mnamici** [comment]
Ho colto l'occasione per aggiungere anche i link al bug tracker e al repository che erano prima accessibili solamente dalla schermata iniziale.

![Screenshot from 2020-01-15 14-22-21](https://user-images.githubusercontent.com/37672765/72437216-88f1d080-37a2-11ea-84bb-631b94c30fb5.png)
