### ISSUE TITLE
Arco InstanceOf

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#45]
Rendere l'etichetta sull'arco InstanceOf aderente all'arco, e permettere di spostare l'etichetta lungo l'arco stesso.

**Comment by valeriosantarelli** [comment]
Mi è arrivata da Maurizio una richiesta che in pratica coincide con l'oggetto di questa issue:

`Sarebbe importante che l'utente potesse scegliere dove piazzare la label "instance-of" associata al corrispondente arco. `

In effetti per ontologie in cui ci sono molti archi istanceof, la situazione attuale è un pò infelice.
A questo punto si potrebbero pensare a diverse soluzioni:

1. Troviamo il modo di rendere la label "instaceof" spostabile, in modo che uno la piazza dove vuole
2. Fare in modo che la label sia parallela all'arco (e non più perpendicolare), e renderla aderente allo stesso, in modo che occupa in pratica pochissimo spazio
3. Modificare proprio l'arco, togliendo la label, e disegnando l'arco in modo da distinguerlo dagli altri due. Questa terza soluzione mi piace di meno perchè comporta un overhead di lavoro lato documentazione e (forse) retrocompatibilità.

Coinvolgo anche @mnamici così ci ragioniamo insieme.

**Comment by NonnonePalmiro** [comment]
Se mi ricordo bene, la gestione degli spostamenti delle label è un po' problematica, e con il semplice spostamento la cosa non credo che migliori molto. Bisognerebbe come minimo dare la possibilità di ruotarle, ma prendere in considerazione la rotazione delle etichette è piuttosto costoso (anche perchè a quel punto dovremmo inventarci un'interfaccia che permetta di farlo con un comando a pop-up tipo quello che c'è in powerpoint, ma credo sai fantascienza per ora...)

A mio avviso la cosa più pulita e meno costosa si ottiene se rimuoviamo le etichette e distinguiamo l'arco cambiando il tipo di linea (tratteggio o simili) o il colore (qualcosa di semplice, tipo grigio)

**Comment by valeriosantarelli** [comment]
Per aggiornare @mnamici : nella call di ieri con @NonnoPalmiro  abbiamo valutato che l'opzione più semplice da implementare in effetti è la modifica dell'arco, rimpiazzando quello attuale con un nuovo tipo di arco che non preveda alcuna label.
Ovviamente il nuovo tipo di arco deve differenziarsi sia da quello di input che da quello di inclusione, quindi potrebbe essere ad esempio un arco tratteggiato con una freccia alla fine.

Prendiamoci qualche giorno per decidere come vogliamo fare l'arco nuovo, dopodichè, se non ci sono suggerimenti alternativi, possiamo procedere.

**Comment by NonnonePalmiro** [comment]
In realtà io già ho apportato la modifica e committato il tutto su develop. L'unico problema è che non partono i build su travis perchè mi sa che dice che dobbiamo cacciare i soldi, parla di "replenish your credit balance to build"

Comunque sono partiti i build su appveyor per Windows, quindi almeno per questo tra un po' ci dovrebbero essere le versioni nuove su JFrog

**Comment by valeriosantarelli** [comment]
Ah ok ottimo, allora a posto.

Sui build non saprei come intervenire...

**Comment by mnamici** [comment]
Ciao ragazzi, ok grazie per l'aggiornamento. Relativamente alle soluzioni proposte mi sembrano più efficaci la 2 e 3  in quanto non introducono incompatibilità con il formato graphol poiché la posizione della label per ora è calcolata automaticamente e non viene salvata. Tra le due probabilmente è solamente una questione estetica, probabilmente la modifica dell'arco per renderlo univoco è la più elegante e, concordo con voi, anche la più semplice da implementare. Per la soluzione 3 magari si può pensare di farlo in stile UML, linea tratteggiata con punta vuota.

**Comment by mnamici** [comment]
Per i build come vi dicevo giorni fa credo dovremmo effettuare la migrazione da Travis a GitHub Actions viste le modifiche apportate da Travis (in sostanza le vm macos sono accessibili tramite una sorta di crediti).
Sto già creando i workflow per github actions. Un paio di pr le ho già integrate infatti i test vengono già fatti per questo repository (se cliccate su Actions potete vedere il workflow attivo), mentre per la produzione dei build nel mio repository ho il workflow per farli ma devo ancora implementare l'upload su bintray. C'è una feature request nel workflow di upload che speravo implementassero in quanto ci semplifica le cose, in alternativa dobbiamo mettere in piedi un meccanismo noi. 
Per ora vengono salvati direttamente su github ma dopo alcuni giorni quelli vengono rimossi. Volendo questo si può già integrare.

**Comment by NonnonePalmiro** [comment]
Ciao Manuel grazie della precisazione e dell'intervento su github. 
Mi ricordavo della problematica con MacOS, ma ora sembra che siano stati disabilitati anche quelli per Linux quindi ho pensato fosse successo qualcos'altro. Per quanto riguarda lo spostamento su gitHub Actions facci sapere se ti serve supporto.

**Comment by mnamici** [comment]
> Mi ricordavo della problematica con MacOS, ma ora sembra che siano stati disabilitati anche quelli per Linux

Sì perché disattivano l'intero build, dovremmo eliminare i job per macos per riattivarlo. In verità è da un pò che volevo fare la migrazione a GitHub Actions che è stato introdotto di recente, così abbiamo tutto sulla stessa piattaforma. Fino ad ora però dato che funzionava bene Travis non ho toccato nulla.
Entro oggi cerco di integrare una prima versione di build automatici con upload sul repository bintray.
