### ISSUE TITLE
Attivazione/disattivazione del Controllo Sintattico

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#48]
Aggiungere un Toggle button per attivare o disattivare il check sintattico dell'ontologia.
Ovviamente l'impostazione di default dovrebbe essere ON.

**Comment by valeriosantarelli** [comment]
Sto rileggendo questa issue e non ne capisco molto il senso.
Se il check sintattico di cui si parla è quello a design-time, che permette di non scrivere cose sbagliate, non capisco quale sia il senso di disattivarlo.

Inoltre, una volta disattivato, cosa ci aspettiamo che succeda in fase di esportazione in OWL? Ovviamente non sarà possibile....

@NonnonePalmiro a meno che non ci viene in mente un motivo particolare per far vivere questa issue, io la chiuderei...

**Comment by NonnonePalmiro** [comment]
Ah a me non viene in mente proprio niente....

**Comment by valeriosantarelli** [comment]
Perfetto, invalido e chiudo.
