### ISSUE TITLE
Dimensione Font

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#49]
Permettere di aumentare/diminuire la dimensione del font delle etichette dei noti.
Va bene anche una cosa semplice, con i pulsanti "aumenta" e "diminuisci", senza gestire tutte le dimensioni possibili.

**Comment by mnamici** [comment]
Un supporto sperimentale alla personalizzazione del font utilizzato nei diagrammi è stato introdotto in 9ff2444.

Per ora è una preferenza dell'utente (non fa parte del file graphol) valida per tutti i diagrammi, ed è accessibile tramite il pannello Preferences.

**Comment by valeriosantarelli** [comment]
Per il momento chiudiamo la issue. Se poi arriveranno richieste di fare qualcosa di più raffinato, lo valuteremo.
