### ISSUE TITLE
Estensione arco instanceOf per meta-livello

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#51]
Permettere di definire archi di instanceOf in modo da definire assiomi di meta-livello.

Ad esempio:
- Classe istanza di un'altra classe
- Coppia di classe istanza di un ruolo
- Attributo istanza di una classe
etc.

Va considerata l'interazione con il check sintattico, e poi anche le problematiche di rielaborazione degli assiomi per una corretta esportazioni in OWL.

**Comment by NonnonePalmiro** [comment]
La funzionalità  è inclusa in versione beta 2.0.0 del 13/03/2020

**Comment by valeriosantarelli** [comment]
Confermo e chiudo.
Non ho potuto verificare l'esportazione in OWL a causa di #75 , quando è risolta quella riprovo.
