### ISSUE TITLE
Importazione di un nuovo progetto

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#52]
Attualmente la schermata iniziale di Eddy propone (oltre all'apertura di un progetto specifico), due opzioni:
1) Creare un nuovo progetto
2) Aprire un progetto

Nessuna di queste due soluzioni è efficace nel caso in cui una persona X passa ad una persona Y un file .graphol, e la persona Y la vuole aprire.

Y ha due opzioni, ambedue non ottimali:
1) Scegliere "Crea un nuovo progetto", inserendo, quando gli vengono chieste, le stesse informazioni presenti nel file .graphol
2) Creare una cartella che si chiama come il file graphol, mettere il file graphol lì dentro, poi scegliere "Aprire un progetto" e selezionare la cartella.

Quello che manca è la possibilità di creare un progetto direttamente a partire dal file graphol. In questo caso il sistema, per non alterare il file system di Eddy, dovrebbe semplicemente creare una cartella nella Eddy_home che si chiama come il file graphol, e copiarci il file dentro.

**Comment by valeriosantarelli** [comment]
Più in generale, sarebbe il caso, una volta per tutte, di poter lavorare con un file .graphol esattamente nello stesso modo in cui si lavora con un file word o un excel o qualsiasi altro file.

Quindi rimuovere la necessità di:

- avere una cartella all'interno della quale si trova il file
- avere che i nomi della (1) cartella, (2) file, e (3) nome dell'ontologia dentro il file siano uguali

Immagino che questa modifica sia abbastanza impattante, ma a differenza di molte altre, sistema una situazione che attualmente è nella pratica veramente scomoda da gestire.

**Comment by NonnonePalmiro** [comment]
Verificare funzionamento distribuzione fornita in data 11/05/2020

**Comment by valeriosantarelli** [comment]
Chiudo e da testare, anche su Windows.
