### ISSUE TITLE
Bug in opening/importing an Eddy file

### ISSUE THREAD

**Issue by savo-fabio** [obdasystems/eddy#53]
When I try to import or open an Eddy file the system returns the following issue: 

Traceback (most recent call last):
  File "C:\projects\eddy-fr441\eddy\plugins\info-v0.3\info.py", line 150, in onSessionReady
  File "C:\projects\eddy-fr441\eddy\plugins\info-v0.3\info.py", line 447, in stack
  File "C:\projects\eddy-fr441\eddy\plugins\info-v0.3\info.py", line 1083, in updateData
  File "C:\projects\eddy-fr441\eddy\core\project.py", line 216, in prefix
TypeError: object of type 'NoneType' has no len()

And no ontology is open or imported

**Comment by valeriosantarelli** [comment]
Sistema operativo Windows.

**Comment by NonnonePalmiro** [comment]
Quando possibile allegate qunato necessario a riprodurre l'errore per favore? (in questo caso file graphol e ,se possibile, eseguibile utilizzato per il lancio del sistema)

**Comment by savo-fabio** [comment]
Errore ottenuto con entrambe le ontologie seguenti: 

 

 <https://github.com/obdasystems/OBDA-Specifications/tree/master/ACI-Open-Data/simple> https://github.com/obdasystems/OBDA-Specifications/tree/master/ACI-Open-Data/simple

https://github.com/obdasystems/OBDA-Specifications/tree/master/movieontology/2.0.0

 

Da: Lorenzo Lepore <notifications@github.com> 
Inviato: Thursday, February 6, 2020 17:17
A: obdasystems/eddy <eddy@noreply.github.com>
Cc: Domenico Fabio Savo <savo.fabio@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [obdasystems/eddy] Bug in opening/importing an Eddy file (#53)

 

Quando possibile allegate qunato necessario a riprodurre l'errore per favore? (in questo caso file graphol e ,se possibile, eseguibile utilizzato per il lancio del sistema)

**Comment by valeriosantarelli** [comment]
La versione di Eddy usata è sia la 1.1.2 develop che la 1.1.2 master, entrambe Windows.

**Comment by valeriosantarelli** [comment]
Aggiungo che anche io ho un errore quando cerco di importare un file Graphol in un progetto esistente (anche vuoto).

L'errore è il seguente:
Traceback (most recent call last):
  File "eddy/ui/session.py", line 1550, in doImport
  File "eddy/core/loaders/graphol.py", line 1933, in run
  File "eddy/core/loaders/graphol.py", line 1906, in projectMerge
  File "eddy/core/project.py", line 2120, in run
  File "eddy/core/project.py", line 1925, in mergeDiagrams
  File "eddy/ui/dialogs.py", line 58, in __init__
  File "eddy/core/common.py", line 1371, in __init__
  File "eddy/core/common.py", line 431, in __init__
TypeError: 'project' is an unknown keyword argument

Ho provato con
https://github.com/obdasystems/OBDA-Specifications/blob/master/ACI-Open-Data/simple/ACIOpenData-current2.graphol
https://github.com/obdasystems/OBDA-Specifications/blob/master/Books/1.0.0/books_ontology.graphol
https://github.com/obdasystems/OBDA-Specifications/blob/master/movieontology/2.0.0/movieontology.graphol

**Comment by NonnonePalmiro** [comment]
A me su sistema windows l'ontologia di imdb viene caricata correttamente. @savo-fabio potresti verificare di aver utilizzato un file graphol corretto  aprendolo con un editor di testo? Nel caso il file sia corretto, potresti allegare direttamente quello che usi tu invece del link github per favore?

**Comment by NonnonePalmiro** [comment]
@valeriosantarelli, siccome a me l'importazione di file graphol in un progetto esistente non da problemi, potresti allegare i file che tu stai effettivamente utilizzando in locale invece dei link di github, avendo cura di specificare quale sia progetto iniziale e quale invece quello importato in un secondo momento? grazie

**Comment by valeriosantarelli** [comment]
> @valeriosantarelli, siccome a me l'importazione di file graphol in un progetto esistente non da problemi, potresti allegare i file che tu stai effettivamente utilizzando in locale invece dei link di github, avendo cura di specificare quale sia progetto iniziale e quale invece quello importato in un secondo momento? grazie

Allego il file (zippato, perchè github non supporta .graphol
), ma è esattamente quello di Github, lo sto proprio prendendo dalla mia copia locale del repository OBDA Specifications.

[movieontology.graphol.zip](https://github.com/obdasystems/eddy/files/4167112/movieontology.graphol.zip)

Questo invece è il progetto iniziale (è vuoto in pratica):
[testtest.graphol.zip](https://github.com/obdasystems/eddy/files/4167121/testtest.graphol.zip)

Domanda: tu stai facendo queste verifiche facendo girare Eddy da ambiente di sviluppo? Perché non vorrei che si trattasse di una problematica già risolta, solamente che il fix non è presente nella release che abbiamo noi (la versione master della 1.1.2 risale a un anno fa, e anche la versione beta della 1.1.2 credo risalga a diversi mesi fa).

**Comment by valeriosantarelli** [comment]
> A me su sistema windows l'ontologia di imdb viene caricata correttamente. @savo-fabio potresti verificare di aver utilizzato un file graphol corretto aprendolo con un editor di testo? Nel caso il file sia corretto, potresti allegare direttamente quello che usi tu invece del link github per favore?

Il file che sta usando @savo-fabio è lo stesso che ho allegato nella issue sopra. Il file è per forza corretto, l'ontologia l'ho creata da zero io tre giorni fa... :D

**Comment by NonnonePalmiro** [comment]
@valeriosantarelli Io le prove le ho fatte con gli eseguibili scaricabili da releases, non da ambiente da sviluppo. In particolare sto usando la versione 1.1.2 per windows a 64bit rilasciata il 12 dicembre 2018, e usando i file allegati da te non ho riscontrato alcun problema. Nel caso persistessero cerchiamo di vederci di persona magari coinvolgendo pure Manuel
 
> Il file che sta usando @savo-fabio è lo stesso che ho allegato nella issue sopra. Il file è per forza corretto, l'ontologia l'ho creata da zero io tre giorni fa... :D
Ho chiesto di verificare che il file fosse corretto perchè se si scarica un file dalla pagina web di github cliccando con il destro direttamente sul file e selezionanado "salva link con nome" si ottiene un file con nome ed estensione corretta ma contenente il codice html della pagina corrispondente al file. 
Chiedendo di allegare l'effettivo file scaricato volemo assicurarmi che non fossimo in questa situazione (visto che già c'ero caduto pur'io a suo tempo).

**Comment by mnamici** [comment]
A giudicare dallo stacktrace ho il sospetto che non c'entri niente il file graphol. @savo-fabio ora hai installato l'ultimo build di sviluppo della 1.1.2? Se sì puoi verificare di non avere due versioni dei plugin installate? I plugin li trovi come archivi zip nella cartella:

 `C:\Program Files\Eddy\plugins` (se hai la versione a 64 bit)

oppure

`C:\Program Files (x86)\Eddy\plugins` (se hai la versione a 32 bit)

In particolare verifica se ci sono due versioni dello stesso plugin, es: `info.zip` e `info-v0.3.zip`.
Se così fosse elimina tutte le copie con il numero di versione appeso alla fine e prova ad aprire di nuovo il progetto.

**Comment by valeriosantarelli** [comment]
> @valeriosantarelli Io le prove le ho fatte con gli eseguibili scaricabili da releases, non da ambiente da sviluppo. In particolare sto usando la versione 1.1.2 per windows a 64bit rilasciata il 12 dicembre 2018, e usando i file allegati da te non ho riscontrato alcun problema. Nel caso persistessero cerchiamo di vederci di persona magari coinvolgendo pure Manuel
> 
> > Il file che sta usando @savo-fabio è lo stesso che ho allegato nella issue sopra. Il file è per forza corretto, l'ontologia l'ho creata da zero io tre giorni fa... :D
> > Ho chiesto di verificare che il file fosse corretto perchè **se si scarica un file dalla pagina web di github cliccando con il destro direttamente sul file e selezionanado "salva link con nome" si ottiene un file con nome ed estensione corretta ma contenente il codice html della pagina corrispondente al file.**
> > Chiedendo di allegare l'effettivo file scaricato volemo assicurarmi che non fossimo in questa situazione (visto che già c'ero caduto pur'io a suo tempo).

Ah in effetti bisogna stare attenti a questa cosa se non si ha una copia locale clonata della repository (come nel caso di Fabio immagino).
Per sicurezza io ho riprovato importando il file proprio dalla cartella di lavoro dove l'ho creato (EddyProjects), ma il risultato è sempre lo stesso.

Comunque certo, vediamoci di persona così proviamo a capire che succede. Io lunedì ci sono tutto il giorno.

**Comment by savo-fabio** [comment]
Risolto! Credo fosse il file. L’ho scaricato di nuovo ed ora va. 

Grazie a tutti per l’aiuto 

Fabio

 

Da: mnamici <notifications@github.com> 
Inviato: Thursday, February 6, 2020 20:29
A: obdasystems/eddy <eddy@noreply.github.com>
Cc: Domenico Fabio Savo <savo.fabio@gmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [obdasystems/eddy] Bug in opening/importing an Eddy file (#53)

 

A giudicare dallo stacktrace ho il sospetto che non c'entri niente il file graphol. @savo-fabio <https://github.com/savo-fabio>  ora hai installato l'ultimo build di sviluppo della 1.1.2? Se sì puoi verificare di non avere due versioni dei plugin installate? I plugin li trovi come archivi zip nella cartella:

C:\Program Files\Eddy\plugins (se hai la versione a 64 bit)

oppure

C:\Program Files (x86)\Eddy\plugins (se hai la versione a 32 bit)

In particolare verifica se ci sono due versioni dello stesso plugin, es: info.zip e info-v0.3.zip.
Se così fosse elimina tutte le copie con il numero di versione appeso alla fine e prova ad aprire di nuovo il progetto.

**Comment by valeriosantarelli** [comment]
@savo-fabio riesci a importare qualsiasi ontologia? Hai provato anche movieontology?

**Comment by savo-fabio** [comment]
Ho controllato, purtroppo non ci sono plugin duplicati. 


Il giorno 6 feb 2020, 20:28, alle ore 20:28, mnamici <notifications@github.com> ha scritto:

**Comment by savo-fabio** [comment]
Ho importato movieontology. Domani proverò con aci

Il giorno 6 feb 2020, 21:57, alle ore 21:57, Valerio Santarelli <notifications@github.com> ha scritto:
