### ISSUE TITLE
Esportazione in PDF

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#54]
Mi sembra che il pulsante "Open File" a valle dell'esportazione (io l'ho fatta in PDF) non faccia nulla quando viene premuto.

<img width="656" alt="Schermata 2020-02-28 alle 09 58 58" src="https://user-images.githubusercontent.com/8250758/75525942-10bd3280-5a11-11ea-8538-3ec85fd1d43e.png">

EDIT: **il problema credo sia che proprio non viene esportato il file (su Mac OSX)**

**Comment by mnamici** [comment]
L'esportazione era infatti bloccata da un problema nel pannello di configurazione della pagina che non è disponibile su macOS per stampanti non native. Ho risolto ricostruendone uno custom.

Se non ci sono problematiche relative al nuovo pannello chiudo la issue.

**Comment by valeriosantarelli** [comment]
Mi pare che stia funzionando tutto, chiudo.
