### ISSUE TITLE
Errore su copia/incolla di un concetto

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#55]
Il sistema riporta un errore sull'azione di copia/incolla di un concetto.

`Traceback (most recent call last):
  File "eddy/ui/session.py", line 2402, in doPaste
  File "eddy/core/clipboard.py", line 185, in paste
  File "eddy/core/project.py", line 388, in copy_IRI_prefixes_nodes_dictionaries
AttributeError: 'NoneType' object has no attribute 'keys'
`

Allego screenshot per mostrare lo stato del diagramma al momento dell'errore:
<img width="940" alt="Schermata 2020-02-28 alle 10 09 29" src="https://user-images.githubusercontent.com/8250758/75526667-7b22a280-5a12-11ea-9f55-26631e0cdcfb.png">

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da versione su Drive 03/03/20

**Comment by valeriosantarelli** [comment]
Confermo, chiudo.
