### ISSUE TITLE
Percorso di accesso per modificare Annotations

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#56]
Credo che bisogna trovare il modo di evidenziare maggiormente dove sta l'opzione di aggiungere/cambiare/eliminare Annotations, adesso è un pò difficile da trovare (se non lo sai ovviamente).

Forse si potrebbe mettere al primo livello del menu contestuale, in considerazione del fatto che un cambio di qualsiasi tipo di Annotation è **per forza** una operazione di refactoring, a differenza magari del cambio di colore che uno potrebbe per qualsiasi motivo mettere due colori diversi su nodi diversi della stessa IRI.
Si potrebbe anche aggiungere un pulsante al menu principale per esempio, tanto i pulsanti lì non fanno mai male.

**Comment by valeriosantarelli** [comment]
Perfetto, il posizionamento va benissimo.
Unica (piccola) osservazione: sarebbe possibile cambiare icona, per differenziarla da quella di Node IRI? Non so se attingiamo da un set di icone predefinite, ma andrebbe bene una qualsiasi icona che rimanda all'idea di scrivere qualcosa. Ad esempio:
https://fontawesome.com/icons/pen?style=solid
https://fontawesome.com/icons/pencil-alt?style=solid
https://fontawesome.com/icons/edit?style=solid

Ovviamente non è urgente, sposto la issue alla milestone 2.2

**Comment by NonnonePalmiro** [comment]
Icona modificata in nuova versione su Drive

**Comment by valeriosantarelli** [comment]
Perfetto!
Chiudo.
