### ISSUE TITLE
Errore successivo a cambio di IRI tramite refactor

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#57]
Il sistema ha restituito il seguente errore quando ho cliccato su un concetto:

2020/02/28 10:18:28 CRITICAL Traceback (most recent call last):
  File "eddy/core/project.py", line 479, in remove_item_from_IRI_prefixes_nodes_dict
AttributeError: 'NoneType' object has no attribute 'keys'

2020/02/28 10:18:30 CRITICAL Traceback (most recent call last):
  File "/Users/lorenzo/eddy/eddy/plugins/info/info.py", line 1916, in editingFinished
AttributeError: 'IRIInfo' object has no attribute 'textField'

La successione di eventi è stata questa:

1. creo un concetto
2. ne creo un altro con la stessa IRI
3. modifico tramite refactor la IRI del concetto, cliccando sul menu contestuale del secondo concetto creato
4. clicco su secondo concetto
5. errore

<img width="908" alt="Schermata 2020-02-28 alle 11 48 06" src="https://user-images.githubusercontent.com/8250758/75542559-5c2b0d00-5a20-11ea-8d0c-b688bd615b56.png">

**Comment by NonnonePalmiro** [comment]
©

**Comment by NonnonePalmiro** [comment]
©

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da versione su Drive 03/03/20

**Comment by valeriosantarelli** [comment]
Confermo, problema risolto.

Per i problemi risolti si può direttamente chiudere, poi col Project (https://github.com/obdasystems/eddy/projects/1) io gestisco la fase di test/conferma risoluzione/eventuale riapertura.

Quando una issue viene chiusa, viene spostata automaticamente da To Do a Review In Progess, poi una volta testata si sposta manualmente in Done.
