### ISSUE TITLE
Sincronizzazione di proprietà di obj props e data props

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#59]
Al momento non c'è sincronizzazione tra i menu contestuale e il widget Info per quanto riguarda la selezione di proprietà di relazioni (quale funzionalità, etc.).
Non è una novità dato che era già stato segnalato il comportamento da @NonnonePalmiro , apro la issue per tracciarla, soprattutto per non dimenticarmi io.

**Comment by NonnonePalmiro** [comment]
Modifica inclusa in build 16/03

**Comment by valeriosantarelli** [comment]
Confermo, chiudo.
