### ISSUE TITLE
Creazione nuovo datatype

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#60]
Attualmente, se seleziono il nodo Datatype dalla Palette e lo inserisco nel diagramma, compare la finestra dell'IRI Builder.

Due osservazioni a riguardo:
- sarebbe più intuitivo se venisse fuori direttamente selezionato il tab Predefined Datatypes, tanto 99 volte su 100 uno vuole scegliere uno di questi
- è veramente necessario in questo caso il tab IRI? Non mi è chiarissimo cosa dovrei farci.

<img width="1153" alt="Schermata 2020-03-01 alle 11 28 02" src="https://user-images.githubusercontent.com/8250758/75623988-45b3bb80-5bb0-11ea-8bae-b972637b8b54.png">

**Comment by valeriosantarelli** [comment]
@valeriosantarelli Valutare se si può utilizzare il nodo dei facets senza usare un user-defined datatype. In caso fosse possibile, si potrebbe anche non permettere di definire i datatype user-defined (almeno per il momemto).

**Comment by valeriosantarelli** [comment]
Io al momento, per gestire la cosa non modo più generico possibile, farei così:

All'inserimento di un nodo datatype nel diagramma, viene fuori l'IRI Builder, che prevede due tab:
- Predefined Datatypes (da visualizzare per primo e già attivato)
- Custom Datatypes (identico all'attuale tab IRI, solo con il nome diverso)

Che ne dici?

**Comment by NonnonePalmiro** [comment]
Mi sembra ragionevole. Appena possibile consideriamo la modifica

**Comment by NonnonePalmiro** [comment]
Modifica inclusa in build 16/03

**Comment by valeriosantarelli** [comment]
Confermo e chiudo.
