### ISSUE TITLE
Errore nel tracciare arco di inclusione tra data prop range a datatype

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#61]
Il sistema ha restituito il seguente errore al momento di agganciare un arco di inclusione dal quadratino nero di un attributo a un datatype:

> Traceback (most recent call last):
  File "/Users/lorenzo/eddy/eddy/plugins/info/info.py", line 111, in onDiagramSelectionChanged
  File "/Users/lorenzo/eddy/eddy/plugins/info/info.py", line 451, in stack
AttributeError: 'InfoWidget' object has no attribute 'infoValueDomainNode'

In allegato lo stato del diagramma la momento dell'errore:

<img width="919" alt="Schermata 2020-03-01 alle 11 31 46" src="https://user-images.githubusercontent.com/8250758/75624014-83184900-5bb0-11ea-8c16-851b857de9ba.png">

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da versione su Drive 03/03/20

**Comment by valeriosantarelli** [comment]
Confermo, ho riprovato a creare la struttura sopra, e non mi ha dato alcun errore. Chiudo.
