### ISSUE TITLE
Prefisso di default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#63]
Si crea una situazione un pò strana nella definizione/visualizzazione del prefisso di default.

In pratica, alla creazione di un nuovo progetto, l'utente mette una IRI e un prefisso, ad esempio:
<img width="586" alt="Schermata 2020-03-01 alle 11 44 35" src="https://user-images.githubusercontent.com/8250758/75624205-8c0a1a00-5bb2-11ea-95e7-f205a119187f.png">

Automaticamente il sistema assegna alla IRI creata anche il prefisso vuoto (:), che lui ritiene essere quello di "default".

<img width="810" alt="Schermata 2020-03-01 alle 11 46 27" src="https://user-images.githubusercontent.com/8250758/75624248-f3c06500-5bb2-11ea-8d8b-e7b37d771000.png">

Se si fa il rendering dell'ontologia per prefixedIRI però, viene utilizzato il prefisso vuoto, non quello definito dall'utente. 
Anche se si prova dall'IRI Builder a cambiare prefisso e assegnare quello definito dall'utente, il sistema usa sempre quello vuoto.

In pratica non c'è modo di utilizzare il prefisso definito dall'utente al momento di creare l'ontologia.

**Comment by NonnonePalmiro** [comment]
Al momento se più prefissi fanno scopa viene sempre data precedenza a quello che ritorna la stringa più corta ( in questo caso ":Ciccio" invece di "test2.0:Ciccio"). Se vuoi si può rendere configurabile (a livello globale) decidendo di ritornare sempre la più lunga o di decidere di dare precedenza ad un prefisso piuttosto che a un altro (anche se nessun altro sistema permette di farlo per quanto ne so). 
Al momento comunque la situazione si risolve rimuovendo il prefisso vuoto

**Comment by valeriosantarelli** [comment]
Si, per il momento credo che vada bene rimuovere la creazione automatica del prefisso vuoto (se è l'utente che lo crea allora è chiaro che va bene).
Così di default c'è un solo prefisso+IRI, e se uno si vuole creare quello vuoto dopo, lo fa.

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da  versione beta 2.0.0 del 13/03/2020

**Comment by valeriosantarelli** [comment]
Confermo. Chiudo.
