### ISSUE TITLE
Ripristino di Switch Type per nodo datatype

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#64]
Ripristinare la funzionalità di Switch Type da menu contestuale per un datatype node.

<img width="786" alt="Schermata 2020-03-04 alle 16 17 57" src="https://user-images.githubusercontent.com/8250758/75893923-c504f180-5e33-11ea-8953-bd26d0bd53f0.png">

**Comment by NonnonePalmiro** [comment]
Facendo doppio click sul nodo, viene riaperta la finestra con i predefined datatypes, non basta quella?  Anche perchè se aggiungiamo la possibilità diu creare User defined Datatypes, come da te suggerito su altro ticket, questo menu potrebbe (in casi estremi) risultare ingestibile per il numero di entries. 

In ogni caso riaggiungere il menu contestuale non sarebbe complicato

**Comment by valeriosantarelli** [comment]
Va bene il funzionamento che c'è attualmente.
