### ISSUE TITLE
Errore creazione nuovo progetto 

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#65]
Alla creazione di un nuovo progetto, il sistema dà il seguente errore:

Traceback (most recent call last):
  File "eddy/ui/project.py", line 248, in accept
  File "eddy/core/exporters/graphol.py", line 641, in run
  File "eddy/core/exporters/graphol.py", line 526, in createOntology
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by NonnonePalmiro** [comment]
Sei sicuro di aver scaaricato l'ultima versione da Drive? Quello era l'errore che restituiva per il bug  che avevo risolto nella scorsa settimana (mi pare che avessimo anche aperto e chiuso una issue a questo proposito). Te lo chiedo perchè il sistema di verisonamento di drive non è che mi stia risultando particolarmente amichevole. Ora provo a inviarti l'ultimo eseguibile per email.  (stesso discorso dovrebbe valere per ticket #66 )

**Comment by valeriosantarelli** [comment]
No, non ne sono sicurissimo in effetti, sto seguendo il link che era nella prima email perchè non mi trovo altri riferimenti su Drive.
Se vuoi puoi usare questa cartella https://drive.google.com/open?id=0B5bmfJmjbWTbUkpuVnNJems4SUE
dove un tempo mettevamo i beta release su drive.

**Comment by NonnonePalmiro** [comment]
Purtroppo come immaginavo ogni volta che aggiungo una versione nuova te la dovrei ricondividere esplicitamente. 
Ora ti ho inviato il link a quella più recente, dalla prossima comincio a usare il repository che mi hai indicato
