### ISSUE TITLE
A capo nelle label dei nodi

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#67]
Non ricordo se avevamo affrontato la faccenda, ma al momento non mi pare sia possibile andare a capo nelle label (se lo è, non so come si fa).

Bisogna trovare un modo per permettere di farlo, senza modificare così facendo la IRI del nodo.

Nell'esempio in screenshot, vorrei poter mandare a capo dentro la label LightCommercialVehicle, dato che va oltre le dimensioni del nodo Class.

<img width="652" alt="Schermata 2020-03-09 alle 15 11 30" src="https://user-images.githubusercontent.com/8250758/76221063-c447d300-6218-11ea-86dc-bc3852cd9d85.png">

**Comment by NonnonePalmiro** [comment]
Quelle che stai visualizzando però non sono label, sono IRI. A mio parere deve essere impedito di andare a capo nella composizione (visualizzazione) delle IRI, perchè quando si visualizza un'identificatore bisogna visulizzare la stringa che effettivamente identifica l'elemento . Secondo me  in questo caso se uno vuole assegna una rdf:label in cui può andare a capo a suo piacimento e visualizza quella. In quest'ottica si potrebbe pensare di consentire all'utente di decidere il tipo di visualizzazione anche solo sul singolo nodo e di scegliere quale rdf:label visualizzare.

**Comment by valeriosantarelli** [comment]
Ah, giusto, hai ragione!
In effetti modificando la label e andando a capo va benissimo.

Eventualmente si potrebbe far scegliere per singolo nodo, però tutto sommato non è indispensabile tutto secondo me.

Questa issue la chiudo
