### ISSUE TITLE
Salvataggio di Annotations e Prefixes

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#68]
Le Annotations non vengono salvate correttamente: alla chiusura e poi riapertura del progetto, non sono più presenti.
In particolare, ho provato con una label.

Edit: aggiungo che anche il salvataggio dei prefissi non avviene in modo corretto. Non sono in verità sicuro che fosse già implementato, comunque lo segno per tenerne traccia.

**Comment by NonnonePalmiro** [comment]
Il problema dovrebbe essere risolto da versione beta 2.0.0 del 13/03/2020

**Comment by valeriosantarelli** [comment]
Confermo. Chiudo.
