### ISSUE TITLE
Modifica di un Namespace associato ad una IRI

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#69]
Una modifica ad un namespace non viene al momento riflessa sulle IRI che sono associate a quel namespace.

Ad esempio: inizialmente li prefisso vuoto (:) era associato al namespace "http://test.com/woc", e tutte le IRI erano associate a questo prefisso.
Mi sono accorto che mancava il separatore al namespace, quindi l'ho aggiunto ("http://test.com/woc#"), ma le IRI nel diagramma sono rimaste associate al namespace "http://test.com/woc", perdendo quindi il prefisso, come si vede dallo screenshot sotto.

<img width="855" alt="Schermata 2020-03-10 alle 20 47 32" src="https://user-images.githubusercontent.com/8250758/76353433-06544000-6311-11ea-9ba7-d5439a62ca2d.png">

Quello che credo dovrebbe succedere è che le IRI associate ad un namespace che viene modificato vengono automaticamente modificate, altrimenti una modifica ad un namespace che viene usato in molte IRI diventa ingestibile.

**Comment by valeriosantarelli** [comment]
Riformulata come enhancement: inserire la funzionalità di refactor di una IRI.
Semplicemente, si dovrà indicare una stringa che in tutte le IRI verrà sostituita con una nuova stringa.

Ad esempio:
http://www.test.com/ -> http://www.test.com#
allora tutte le IRI che iniziano con http://www.test.com/ ora inizieranno con http://www.test.com#

**Comment by NonnonePalmiro** [comment]
Modifica inclusa in build 16/03

**Comment by valeriosantarelli** [comment]
Ok mi pare che funzioni tutto correttamente.

Ho fatto refactor di una IRI verso una nuova IRI (corretto), sui nodi quindi sono comparsi tutte le IRI complete (perchè non c'era un prefisso assegnato alla nuova IRI), quindi ho assegnato un prefisso già esistente alla nuova IRI (e di nuovo si vedono le IRI prefissate sui nodi).

Chiudo.
