### ISSUE TITLE
Prefisso "default" già selezionato

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#71]
Nell'IRI Builder, sarebbe comodo avere già selezionato il prefisso di default (ovvero semplicemente quello che si associa al namespace quando viene creata l'ontologia), dato che è quello che viene utilizzato di più.
Questo eviterebbe di andare ogni volta a selezionarlo dal menu a tendina.

**Comment by NonnonePalmiro** [comment]
Questo dovrebbe già essere implementato nella verisone corrente
