### ISSUE TITLE
Annotations nell'IRI Builder per nuova entità

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#73]
Sarebbe comodo che al momento di inserire una nuova entità nell'ontologia, comparisse anche il tab Annotations dentro l'IRI Builder.

In questo modo, se lo si ritiene opportuno, si può immediatamente ad esempio inserire una label, invece di dover definire prima la IRI, poi riaprire l'IRI Builder e andare sul tab Annotations.
Questo è particolarmente utile sia nei casi in cui si sa che l'ontologia sarà multilingua (quindi con tutte label) sia nei casi di nomi lunghi che si vuole spezzare su più righe.

<img width="780" alt="Schermata 2020-03-14 alle 19 45 32" src="https://user-images.githubusercontent.com/8250758/76688400-986b8980-662c-11ea-81d3-39d04f094a94.png">

**Comment by NonnonePalmiro** [comment]
In realtà questa funzionalità è stata estromessa appositamente (come in tutti gli altri sistemi di gestione di ontologie, dove prima si crea l'entità, e solo successivamente si predica su di essa).

Quello che proponi tu secondo me sarebbe corretto se questa particolare'interfaccia (quella che appare dopo drag and drop dalla palette e col doppio click sul nodo)  fosse usata solo per creare elementi nuovi (IRI non già nominate altrove) e quindi si prevedesse di non consentire l'inserimento di identificatori già nominati nell'ontologia. Altrimenti si potrebbero creare situazioni strane in cui fai refactoring di nodi già esistenti tramite il drag and drop di elementi vuoti dalla palette: 
ad esempio supponi abbia già creato un concetto  l'IRI "http/ciccio.com/el#iri_1" e gli ho associato le annotations ann_1 e ann_2, poi faccio drag and drop di un concetto vuoto e nell'interfaccia inserisco la stringa "http/ciccio.com/el#iri_1", a quel punto tutto quello che faccio nel tab annotations va a sovrascrivere quanto fatto in precedenza. 

In sintesi secondo me non renderebbe abbastanza chiara la distinzione tra operazioni che hanno come uno scope locale relativo ad un singolo nodo (trascinamento dalla palette o doppio click in cui si associa una IRI ad un nodo del grafo) e le operazioni che hanno come uno scope globale, e cioè il predicare su di una IRI che può essere associata a un numero qualunque di nodi del grafo. 

Sintetizzando, l'implementazione di quanto richiesto non sarebbe complicata, quindi se lo si ritenesse opportuno potrebbe essere aggiunta facilmente, ma io personalmente non lo farei a meno di considerare una modifica più ampia ai meccanismi di interazione. 

Analoga considerazione vale per issue #74 ( a parte la richiesta relativa alla  lingua di default per l'ontologia, che è slegata da tutte le considerazioni fatte sopra).

**Comment by valeriosantarelli** [comment]
L'osservazione è giusta: in effetti al momento l'IRI Builder non dà evidenza del fatto che si sta creando una IRI nuova oppure si sta aggiungendo un ulteriore nodo di una già esistente (e forse non serve nemmeno questa cosa). Quindi si potrebbe generare un pò di confusione nella creazione di annotazioni.
Al momento possiamo lasciare così (tolgo la issue dal milestone), poi vediamo dal feedback che ci arriva con più di un utente (cioè io.. :D) se serve rendere più agevole il meccanismo.

Riguardo alla issue #74, ho una proposta alternativa, che aggiungo ai commenti di là.
