### ISSUE TITLE
Label di Default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#74]
Sarebbe MOLTO comodo poter prevedere un meccanismo che (solo se l'utente lo vuole) permette in automatico di aggiungere una label al momento di creare una nuova entity nel diagramma.

Questo meccanismo credo debba prevedere queste due cose:
- la possibilità di definire una lingua di default per l'ontologia (non per l'utente, proprio per l'ontologia) in cui la label verrà creata
- che la label coincida con quello che l'utente scrive dentro il campo INPUT della form dell'IRI Builder (o, al peggio, con il Simple Name, ovvero con quello che c'è dopo l'ultimo separatore nella IRI)

Immagino una cosa tipo una checkbox dentro l'IRI Builder con etichetta "Create label" sotto la voce Full IRI della form.

<img width="780" alt="Schermata 2020-03-14 alle 19 45 32" src="https://user-images.githubusercontent.com/8250758/76688483-83432a80-662d-11ea-9fe9-95c5ae56f80c.png">

**Comment by valeriosantarelli** [comment]
In considerazione dei commenti nella issue #73 , ho una proposta alternativa.

L'obiettivo della issue era in sostanza inserire un meccanismo che evitasse ad un utente di dover scrivere a mano tutte le label, nella situazione in cui le label coincidono sempre (o quasi sempre) con il simple name dell'entity.
Se fare questa operazione nel contesto dell'IRI Builder può generare confusione, si potrebbe in alternativa inserire da qualche parte (Ontology Manager?) un pulsante "Create Default Labels" (o qualcosa del genere) che non fa altro che, per tutte le entity che NON hanno una label, crearne una nella lingua di default dell'ontologia, coincidente con il simple name.

Quindi ad esempio se nell'ontologia, con lingua di default inglese, ci sono 50 entity, di cui 3 hanno una label e gli altri 47 no, premendo questo pulsante, verrebbero generate 47 label @en che hanno come contenuto i rispettivi simple name delle entità.
In questo modo, con un solo click, si risolve il problema di creare tutte le label. Poi ovviamente se bisogna andare a capo o fare altre modifiche su qualcuna, si fa a mano una per una, ma almeno così uno si è tolto il grosso.

**Comment by NonnonePalmiro** [comment]
Io al momento sto andando in questa direzione: ho aggiunto un pannello nell'ontology manager con una checkbox che, se selezionata, ogni volta che viene creata una nuova IRI aggiunge a questa anche l' rdfs:label valorizzata con il simplename e con la lingua di default dell'ontologia (sempre selezionabile dalla stessa interfaccia). Al momento ho fatto solo il pannello e devo implementare bene le funzionalità, quindi se possibile fammi sapere se ti sembra un percorso accettabile. (Considera anche che in caso il bottone che descrivi tu può essere sempre aggiunto alla stessa interfaccia)

**Comment by NonnonePalmiro** [comment]
Aggiungo che, se vuoi farti un'idea, il nuovo pannello è incluso nell'ultimo build caricato su Drive

**Comment by valeriosantarelli** [comment]
> Io al momento sto andando in questa direzione: ho aggiunto un pannello nell'ontology manager con una checkbox che, se selezionata, ogni volta che viene creata una nuova IRI aggiunge a questa anche l' rdfs:label valorizzata con il simplename e con la lingua di default dell'ontologia (sempre selezionabile dalla stessa interfaccia). Al momento ho fatto solo il pannello e devo implementare bene le funzionalità, quindi se possibile fammi sapere se ti sembra un percorso accettabile. (Considera anche che in caso il bottone che descrivi tu può essere sempre aggiunto alla stessa interfaccia)

Si, direi che va benissimo! Domani scarico la nuova versione gli dò un'occhiata.

**Comment by valeriosantarelli** [comment]
Secondo me il pannello va bene, soddisfa pienamente l'esigenza di non dover per forza creare a mano tutte le label.

**Comment by valeriosantarelli** [comment]
Perfetto. Chiudo.
