### ISSUE TITLE
Errore Esportazione OWL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#75]
L'esportazione in OWL dell'ontologia in allegato ha restituito il seguente errore:

Traceback (most recent call last):
  File "eddy/core/exporters/owl2_iri.py", line 723, in run
  File "eddy/core/exporters/owl2_iri.py", line 1751, in addAnnotationAssertions
AttributeError: 'IRI' object has no attribute 'iri'

Specifico che nell'ontologia ho definito delle annotations sull'ontologia (non so se può aver generato quello l'errore).

Ovviamente se l'esportazione non è ancora supportata per Eddy v2 del 13/3/2020 si può ignorare la issue.

[WolfOil.zip](https://github.com/obdasystems/eddy/files/4333220/WolfOil.zip)

**Comment by NonnonePalmiro** [comment]
Modifica inclusa in build 16/03

**Comment by valeriosantarelli** [comment]
L'esportazione in OWL degli assiomi mi pare corretta. Ho provato anche a creare una ClassAssertion tra due classi, e l'owl mi pare giusto.

C'è qualcosa che non mi è del tutto chiaro però nell'esportazione delle annotazioni. L'OWL prodotto è il seguente:

Prefix(:=<http://www.obdasystems.com/>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(woc:=<http://www.obdasystems.com/>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)

Ontology(<http://www.obdasystems.com/>

<http://www.obdasystems.com/1.0>
Declaration(Class(woc:CommercialVehicle))
Declaration(Class(woc:LightCommercialVehicle))
Declaration(Class(woc:PassengerCar))
Declaration(Class(woc:Vehicle))
Declaration(NamedIndividual(woc:LightCommercialVehicle))
Declaration(AnnotationProperty(woc:author))
**CommercialVehicle)**
AnnotationAssertion(rdfs:label woc:LightCommercialVehicle "Light
CommercialVehicle"@en)
EquivalentClasses(woc:Vehicle ObjectUnionOf(woc:CommercialVehicle woc:LightCommercialVehicle woc:PassengerCar))
**CommercialVehicle)**
ClassAssertion(woc:Vehicle woc:LightCommercialVehicle)
DisjointClasses(woc:CommercialVehicle woc:LightCommercialVehicle woc:PassengerCar)
AnnotationAssertion(woc:author <http://www.obdasystems.com/> "Valerio Santarelli"@en)
AnnotationAssertion(rdfs:comment <http://www.obdasystems.com/> "Ontologia per i dati TecDoc nel progetto WolfOil."@it)
AnnotationAssertion(rdfs:comment <http://www.obdasystems.com/> "Ontology for the TecDoc data in the WolfOil project"@en)
)

Le tre annotations definite sull'ontologia sono giuste, quella definita sulla classe LightCommercialVehicle anche,  ma non capisco cosa sono quelle due righe evidenziate. Non vorrei che l'essere andato a capo dentro l'annotation di LightCommercialVehicle abbia creato qualche problema.

Allego .owl e .graphol
[WolfOil.zip](https://github.com/obdasystems/eddy/files/4342933/WolfOil.zip)
[WolfOil.owl.zip](https://github.com/obdasystems/eddy/files/4342931/WolfOil.owl.zip)

**Comment by valeriosantarelli** [comment]
Confermo e chiudo.
