### ISSUE TITLE
Aggancio sul bordo di un nodo

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#76]
Nella versione 2 di Eddy non sembra essere possibile agganciare (in input o output) un arco sul bordo di un nodo. Il puntamento dell'arco va sempre a cercare il baricentro del nodo.
Nelle versioni precedenti di Eddy (inclusa la 1.2) questo non avviene, si riesce ad agganciare l'arco su qualsiasi punto del nodo.

Ad esempio, nell'immagine sotto vorrei rendere retto l'arco input che va in uscita da woc:Vehicle.
![Schermata 2020-03-17 alle 11 59 40](https://user-images.githubusercontent.com/8250758/76850031-d17f4600-6846-11ea-8fb2-5e167b457198.png)

**Comment by NonnonePalmiro** [comment]
Io non riesco a ricrear la situazione descritta nemmeno nella versione 1.1.2 , ogni volta che intervengo sugli archi questi puntano direttamente al centroide dell'elemento cui si sta agganciando l'arco. C'è qualche accorgimento che devo prendere per eseguire l'operazione in oggetto (tipo tenere premuto Command+Alt o simili) ?
