### ISSUE TITLE
Posizionamento dei label

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#79]
Mi sono reso conto che i label sui nodi (di qualsiasi tipo, IRI, prefixedIRI, o proprio label), se vengono spostati, alla successiva apertura di Eddy poi vengono riportati alla posizione originale.

Ad esempio, guarda i due screenshot sotto (stessa ontologia, subito prima e subito dopo la chiusura e riapertura di Eddy): i label di diversi ruoli sono stati riportati al centro del nodo, così come la prefixedIRI del concetto woc:Manufacturer.

![Schermata 2020-03-21 alle 19 28 58](https://user-images.githubusercontent.com/8250758/77233856-a67c5580-6baa-11ea-83ae-ee747921d79f.png)

![Schermata 2020-03-21 alle 19 29 40](https://user-images.githubusercontent.com/8250758/77233863-aaa87300-6baa-11ea-9f02-f1734e948048.png)

**Comment by valeriosantarelli** [comment]
Ho riprovato, e in effetti i label non vengono riposizionati più al centro del nodo.
Però adesso si ha come un effetto contrario: vengono spostati rispetto al piazzamento deciso dall'utente.

Prima di chiudere:
![Schermata 2020-03-23 alle 11 17 32](https://user-images.githubusercontent.com/8250758/77306568-28c66000-6cf8-11ea-8df3-9ed5c067d6bb.png)

Dopo aver riaperto:
![Schermata 2020-03-23 alle 11 18 06](https://user-images.githubusercontent.com/8250758/77306592-31b73180-6cf8-11ea-8584-14a95d4f8310.png)

**Comment by valeriosantarelli** [comment]
@mnamici @NonnonePalmiro Ragazzi, io e Giacomo ci siamo accorti che il problema del posizionamento del label è presente già nella versione 1.2 di Eddy.

Ho fatto una prova stupidissima, inserendo un concetto e un attributo, e spostando la label, e alla successiva riapertura le etichette sono spostate.

A questo punto è urgente trovare una soluzione più rapidamente possibile e fare un nuovo rilascio, perchè stiamo già usando Eddy per il progetto con Inail. Valutate voi, non appena il problema è risolto, se è il caso di fare direttamente un rilascio della 3.0, oppure una release 1.3.

**Comment by mnamici** [comment]
> @mnamici @NonnonePalmiro Ragazzi, io e Giacomo ci siamo accorti che il problema del posizionamento del label è presente già nella versione 1.2 di Eddy.

Ciao ragazzi, sto provando a riprodurre il problema nella 1.2 ma non ci riesco, riepilogo gli step che ho provato:

1) Creato nuovo progetto e creato un diagramma.
2) Inserito un nuovo concetto
3) Inserito un nuovo attributo
4) Spostato entrambe le label fuori dalla posizione di default.
5) Chiuso e riaperto il progetto più volte ma la posizione rimane corretta.

Puoi elencarmi esattamente gli step che avete seguito per riprodurre la issue?

**Comment by NonnonePalmiro** [comment]
Io ho appena scaricato la 1.2 da drive e anche a me funziona bene

**Comment by valeriosantarelli** [comment]
Ho scaricato anche io ex-novo la 1.2, e fatto esattamente gli stessi passaggi che ha elencato Manuel, e in effetti rimane tutto a posto.
Prima avevo fatto gli stessi passaggi, e il comportamento era diverso.

Non ho idea del perchè questo fenomeno si stia verificando nell'ontologia che vedete in allegato.
L'unica cosa che ha di particolare (da quello che riesco a vedere) è che in questa ontologia ci sono delle occorrenze di label dei nodi **concetto** che sono stati spostati fuori dal rettangolo.
[INAIL.zip](https://github.com/obdasystems/eddy/files/4566489/INAIL.zip)

@giacomoronconiobda potresti fare una prova scaricandoti ex-novo la versione 1.2, sistemando un pò dei label spostati, e vedendo se vengono rispostati alle successive aperture?

**Comment by giacomoronconiobda** [comment]
Il problema potrebbe essere lo stesso evidenziato dal parser di mastro:
poiché abbiamo importato dei diagrammi dall'ontologia Aci sembra ci siano
dei nodi diversi con lo stesso id. Forse questo porta allo spostamento dei
label. L'ontologia Inail sta qui su git.

Il sab 2 mag 2020, 00:39 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
La issue è risolta a partire dal build del 26/05/2020. Chiudo.
