### ISSUE TITLE
Errore creazione nuova entità dopo modifica prefix default

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#84]
Questa sequenza di operazioni ha dato origine all'errore che riporto sotto:

1. Creazione di un concetto test2.0:C1 (nome prefissato ovviamente, con test2.0 assegnato al namespace di default)
2. Creazione di un concetto test2.0:C2
3. Modifica del prefisso test2.0 nel prefisso vuoto (questo ha correttamente modificato le due classi in :C1 e :C2
4. Inserimento di un ruolo nuovo nel diagramma

Step 4 ha generato l'errore. Ho riprovato anche inserendo altri tipi di nodo, sempre stesso errore.

Traceback (most recent call last):
  File "eddy/core/diagram.py", line 203, in dropEvent
  File "eddy/ui/session.py", line 2270, in doOpenIRIBuilder
  File "eddy/ui/iri.py", line 191, in __init__
  File "eddy/core/owl.py", line 1405, in getNamespace
KeyError: 'test2.0'

**Comment by NonnonePalmiro** [comment]
Il prefisso "test2.0" era quello inserito al momento della creazione del progetto insieme all'IRI dell'ontologia?

**Comment by valeriosantarelli** [comment]
Si, esatto.

**Comment by NonnonePalmiro** [comment]
Il problema è risolto. Aggiungo label per tenere traccia di modifiche effettuate dopo che manuel ha preso in carico operazioni di Merge.
Moduli modificati: 
- eddy/ui/iri.py
-eddy/ui/ontology.py
-eddy/core/commands/project.py

**Comment by mnamici** [comment]
Backport delle modifiche effettuato. 

Per il momento lasciamo la issue aperta, la chiudiamo dopo aver testato il merge.
