### ISSUE TITLE
Dimensione font per singolo nodo

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#85]
Come prevedibile, Maurizio suggerisce di permettere di definire la dimensione del font per singolo nodo (oppure singola IRI immagino, sarebbe più comodo).
In pratica:
- aggiungere la dimensione del font a quelle proprietà che si possono settare per singolo nodo o tramite refactoring (tipo il colore per intenderci)
- permettere tramite le impostazioni generali di settare (o resettare) tutte le dimensioni ad un font generale

**Comment by mnamici** [comment]
Allora probabilmente è il caso di gestirle non come preferenze dell'utente ma come proprietà del singolo nodo, salvandole nel file graphol (in effetti esattamente come avviene per il colore).

Si potrebbe creare un tab "appearance" nelle proprietà del nodo ed inserire lì font e colore.
Teniamolo presente prima di finalizzare la nuova struttura del file graphol.
