### ISSUE TITLE
Cardinality restriction

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/eddy#86]
Se si creano  cardinality restriction il sistema va in errore non gestito
<img width="564" alt="Schermata 2020-03-27 alle 12 30 41" src="https://user-images.githubusercontent.com/46748150/77751895-ceded680-7026-11ea-9a79-707c3d43a5a8.png">

**Comment by mnamici** [comment]
L'errore è presente nella versione rilasciata o nel branch delle IRI?

**Comment by NonnonePalmiro** [comment]
L'errore è nel branch delle IRI, continua ad essere chiamata la funzione predicates() che è stata sostituita da altra funzione del nuovo indice. La cosa è di facile risoluzione ma non ho voluto apportare la modifica prima di avere notizie definitive sul merge visto che nessun'altro al momento usate cardinality restriction, così ho aperto il ticket giusto per tenerne traccia
