### ISSUE TITLE
Modifiche rappresentazione Graphol

### ISSUE THREAD

**Issue by mnamici** [obdasystems/eddy#87]
Apro questa issue per segnalare un problema a livello di modellazione
che ho riscontrato nella fase di merge delle modifiche per il
supporto alle IRI, ed in generale come spunto di discussione per considerare  
ulteriori modifiche alla struttura del nuovo file Graphol prima della sua finalizzazione
che si riflette poi nella rappresentazione in memoria di Eddy.

In sostanza ho notato che ora assiomi logici riguardanti 
i predicati (funzionalità, transitività, ecc..) 
vengono associati a ciascuna IRI che compare nel progetto, 
a prescindere da quale sia il suo utilizzo, ad es. se rappresenta 
un identificatore di ruolo, attributo, ma anche classe, individuo, datatype, 
facet, o annotation property, per i quali queste proprietà non
hanno significato. Di per sé questo rappresenta già un problema per la
nuova rappresentazione in quanto non so che senso abbia gestire
queste informazioni per IRI che non rappresentano ruoli o attributi
(ma ci si potrebbe convivere).

La parte rilevante però è che questa cosa comporta una regressione significativa
in quanto così facendo non riusciamo più a differenziare, 
qualora la stessa IRI compaia sia come ruolo, sia come attributo, 
a quale dei due la funzionalità si riferisca.
A meno che non si voglia mettere in piedi un meccanismo per evitare questo utilizzo
(cosa che dubito considerato tutto il discorso sul supporto al punning)
credo sia il caso di soffermarsi e rivedere la rappresentazione.
Di seguito un esempio di come si presenta il problema:

![bug-functional](https://user-images.githubusercontent.com/37672765/77853814-8241f980-71e6-11ea-863e-1f98b857f5b1.gif)

A tal proposito vorrei cominciare proponendo una possibile soluzione:
Poiché i meccanismi per tale differenziazione erano già in piedi io
proporrei con il ripartire da quelli, modificando, ove necessario,
per rendere esplicite le occorrenze delle IRI. Ad esempio, considerando 
un semplice progetto con un ruolo ed un attributo identificati dalla stessa IRI, 
la rappresentazione Graphol v2 produrrebbe la seguente struttura relativa ai predicati:

```xml
<!-- ... -->
<predicates>
  <predicate type="role" name=":myresource">
    <description status=""></description>
    <functional>0</functional>
    <inverseFunctional>1</inverseFunctional>
    <asymmetric>0</asymmetric>
    <irreflexive>0</irreflexive>
    <reflexive>0</reflexive>
    <symmetric>0</symmetric>
    <transitive>0</transitive>
  </predicate>
  <predicate type="attribute" name=":myresource">
    <description status=""></description>
    <functional>1</functional>
 </predicate>
</predicates>
<!-- ... -->
```

Ora i problemi con questa rappresentazione sono che la descrizione non è un assioma logico,
bensì un'annotazione e quindi non ha motivo di presentarsi in questa sezione, e che i
nomi dei predicati sono derivati dai label dei nodi con prefisso, il che comporta tutta
una la serie di problematiche che abbiamo già affrontato diverse volte.
Introducendo ora il meccanismo "guidato" di assegnazione delle IRI ai nodi, possiamo fare
sempre uso esplicito delle IRI all'interno della sezione predicati, senza dover ogni
volta ricavarle dal testo, il che risolve il secondo problema 
(da notare che è lo stesso meccanismo utilizzato per il formato RDF/XML).
Per quanto riguarda la descrizione, questa deve diventare un'annotazione da riportare
nella sezione annotazioni, eventualmente valutando la possibilità di definire una nostra
annotazione `graphol:description` o semplicemente trasformandola in `rdfs:comment`, a noi la scelta.
Lo stato è un'annotazione dell'istanza di annotazione se vogliamo riportarlo.
I nodi riportano già il riferimento alla iri quindi rimane fuori la preferenza di
visualizzazione che è associata alle preferenze utente, come già avviene.
A seguito di questa modifica la sezione `iris` che ha sostituito `predicates` in realtà
non occorre più in quanto le rimenenti IRI sono specificate nelle relative sezioni, ad esempio
datatypes, annotationProperty, ecc...

In pratica la nuova versione potrebbe diventare come segue:
```xml
<!-- ... -->
<predicates>
  <predicate type="role" name="http://example.com/myontology/myresource">
    <inverseFunctional/>
  </predicate>
  <predicate type="attribute" name="http://example.com/myontology/myresource">
    <functional/>
 </predicate>
</predicates>
<!-- ... -->
<annotations>
  <rdf:Description rdf:about="http://example.com/myontology/myresource">
    <rdfs:label xml:lang="en">My Resource</rdfs:label>
    <graphol:description xml:lang="en"> 
      This is the description of the role :myresource.
    </graphol:description>
    <graphol:description xml:lang="en"> 
      This is the description of the attribute :myresource.
    </graphol:description>
  </rdf:Description>
</annotations>
<!-- ... -->
```

Da notare che ho eliminato i valori di default, unificato vecchie descrizioni di ruolo ed attributo,
ed usato il formato RDF/XML per la serializzazione delle annotazioni in quanto effettivamente potremmo 
fare uso di quello senza reinventare la ruota (e soprattutto non ricordo ora qual'è quello 
attualmente utilizzato, quindi abbiate pazienza :-) ).

In sostanza rispetto alla situazione attuale i cambiamenti da apportare sarebbero i seguenti:

* Eliminazione degli assimi logici dalla classe IRI (di fatto la rendiamo un'astrazione di valore).
* Ripristino vecchio sistema `meta` per tenere traccia di questi ultimi (riguardo a questo punto sono
  molto tentato di valutare l'introduzione di una libreria come **rdflib** che ci darebbe gratuitamente in-memory storage, query e serializzazione per le annotazioni, ma anche un semplice dizionario per IRI potrebbe essere sufficiente per ora).
* Eliminazione sezione `iris` a questo punto non più necessaria.
* Aggiornamento loader/exporter.

A questo punto vorrei chiedere vostri pareri/osservazioni/correzioni a riguardo.

Se per voi va bene vorrei prendere carico io di questa questa modifica dato che sto facendo il merge con il branch stabile.

**Comment by valeriosantarelli** [comment]
Il problema segnalato da Manuel mi sembra significativo, ovviamente con maggiore rilevanza rispetto al discorso delle proprietà assegnate alle IRI invece che al loro utilizzo come ruoli e/o attributi.

Per quanto non mi entusiasmi il dover rimettere mano alla struttura del file .graphol, mi pare quindi che una esigenza ci sia in questo senso. A questo punto forse è il caso di fare una valutazione globale, come suggerisce Manuel, per ottimizzare la rappresentazione stessa. Ovviamente io non sono in grado di valutare quello che sia l'impatto di questi interventi sul codice, gli unici spunti che posso da sono:

1. non c'è una scadenza immediata per il rilascio della 2.0, quindi se dobbiamo prenderci una settimana in più facciamolo. Però allo stesso tempo cerchiamo di arrivare in tempi ragionevoli ad una rappresentazione definitiva, anche perchè bisogna considerare un nuovo ciclo di test a valle di ulteriori modifiche
2. consideriamo sempre che una modifica della struttura del file graphol genera in cascata modifiche a Grapholscape, e al parser Graphol-> OWL dentro Mastro. Quindi cerchiamo di definire una volta per tutte la struttura del graphol v3 così poi non dobbiamo fare rollback anche su questi altri strumenti.

Mi permetto di inserire un paio di ulteriori suggerimenti rispetto ad aspetti ottimizzabili del file graphol:

- sezione Datatypes: attualmente questa sezione riporta tutti i datatype, sia quelli predefiniti che quelli user-defined. Il mio suggerimento sarebbe quello di eliminare da questa lista quelli predefiniti, in quanto inutili, e lasciare solamente quelli user-defined. Questo credo sarebbe anche comodo da gestire dentro Eddy, perchè agevolerebbe la distinzione tra quelli predefiniti e quelli definiti dall'utente, cosa che al momento non avviene. Tra l'altro ho fatto una prova eliminando dal file quasi tutti i Datatypes predefiniti, e Eddy funziona lo stesso, quindi non credo li usi manco Eddy stesso.
- sezione Facets: siccome non prevediamo (nè prevederemo) la possibilità di definire facets nuovi da parte dell'utente, credo che questa sezione si possa togliere
- sezione AnnotationProperty: stessa considerazione fatta nella sezione Datatypes

Comunque se vogliamo discuterne a voce, io sono disponibile sempre.

**Comment by NonnonePalmiro** [comment]
A mio parere credo si stia confondendo la sintassi (finalità alla quale è rivolta Eddy) con la semantica (cosa che a Eddy non interessa, tanto è vero che viene delegata ad altri strumenti). Riguardo alla problematica relativa a ruoli-attribut,i quando una stessa IRI viene usata come ruolo e come attributo in un'ontologia OWL:
- se viene utilizzata con la Direct Semantics (basata su DL), allora l'ontologia è illegale, e nessun assioma viene preso in considerazione;
- se viene utilizzata la RDF Semantics, allora non esiste alcuna distinzione tra ruoli ed attributi e dunque se viene dichiarata la funzionalità su un "rombo" o su un "cerchietto", questa deve essere riportata anche sull'altro elemento grafico.
In ultima istanza, in entrambi i casi quando si predica su un'identificatore si predica su tutti gli elementi che sono riferibili all'identificatore stesso. Reintrodurre le varie sezioni "role", "attribute", etc, ci riporta verso un'incorporazione della semantica, e questa cosa a mio avviso va evitata.

Per quanto riguarda le considerazioni riguardanti solo la serializzazione del progetto:
- come già discusso in precedenza, volendo si può evitare di riportare esplicitamente gli "zeri" nella sezione <iris>, presupponenedo che  qualora manchi per esempio il tag <symmetric> questo implichi che se l'elemento viene interpretato come una proprietà, allora questa non è simmetrica;
-  per quanto riguarda Datatypes, Facets ed AnnotationProperties, le sezioni erano state pensate per dare la possibilità (ora implementata solo per le annotation properties che possono essere eliminate tramite l'ontology manager) all'utente di impedire di default l'utilizzo di alcuni elementi nel contesto di un dato progetto (ad esempio qualora non voglia che nell'ontologia venga usato xsd:integer, ma solo xsd:int).

**Comment by valeriosantarelli** [comment]
Al termine della conversazione odierna, le decisioni prese sono le seguenti:
- lasciare inalterata l'attuale implementazione che prevede di assegnare la funzionalità come proprietà di una IRI
- prevedere un check (analogo a quello per il profilo OWL) che determina la compatibilità con la semantica DL dell'ontologia
- adottare la versione 3.0.0 per il prossimo rilascio di Eddy, per allinearlo con la sintassi di graphol che compare all'interno del file .graphol
- prevedere la possibilità di rimuovere da Eddy dei datatype predefiniti dal progetto (lasciando nel file .graphol quindi l'elenco dei datatype)
- rimuovere dalla sezione IRI tutte le voci relative ai datatype/annotation properties
- spostare eventuali annotazioni su datatypes dentro il corrispondente tag nella sezione datatypes
- togliere il tag annotations se è vuoto
- togliere i tag delle proprietà il loro valore è pari a 0

Mi pare tutto, vedete se vi torna, e se mi sono perso qualcosa in caso integrate.
