### ISSUE TITLE
Creazione automatica delle label

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#88]
C'è un piccolo problema nella creazione automatica delle label che si verifica quando il namespace utilizzato nell'IRI non termina con un separatore (/ o #) 
Prendo ad esempio il namespace associato al prefisso "xml" (che non usiamo nei predicati ma vabbè, è a titolo di esempio).
Il namespace è http://www.w3.org/XML/1998/namespace, e il prefisso ""xml".
Se quindi definisco una classe xml:Class1, il sistema costruisce la label non come Class1, ma come "namespaceClass1", perchè immagino vada a troncare sull'ultimo separatore.

Credo che questa cosa si risolva andando a fare un confronto con la porzione di stringa utilizzata come namespace dentro la definizione di un prefisso.

**Comment by NonnonePalmiro** [comment]
Se un'iri è identifata dalla stringa  http://www.w3.org/XML/1998/namespaceClass1 , allora il suo simpleName è "namespaceClass1". Come già detto in altre occasioni, non vi è alcuna correlazione esplicita fra gli identificatori che compaiono nell'ontologia e i prefissi dichiarati nell'ontologia stessa. Se ho capito bene, si sta proponendo di implementare qualcosa di diverso da un label associato al simple name, ma si sta chiedendo di provare a far combaciare una sottostringa dell'identificatore con i prefissi dichiarati per poi sceglierne uno tra quelli che hanno un match positivo.

**Comment by valeriosantarelli** [comment]
Si, in sostanza il punto è quello (mi scuso se non ero stato chiaro al momento di definire il requisito).
Tutto nasce ovviamente da una esigenza pratica: se decido che voglio fare il rendering per label (o comunque se decido di produrre una ontologia con dei label), sarebbe comodo non dover definire una per una le label di tutte le entità, nei limiti in cui la label combacia con quello che scrivo nel campo "Input" dell'IRI Builder (se non combacia oppure se va modificato vabbè quello si fa a mano).
A questo punto quello che mi aspetterei da utente diciamo è che il contenuto della label sia esattamente quello che scrivo nel campo Input, qualsiasi cosa esso sia.
Eventualmente questa possibilità può essere in aggiunta, e non in sostituzione di quello che c'è adesso, che in effetti fa esattamente quello che c'è scritto che fa (ovvero ricavare la label dal simpleName).

**Comment by NonnonePalmiro** [comment]
Che c'entrano le scuse, era solo per vedere se avevo capito bene...
Dunque stiamo dicendo di aggiungere un'ulteriore checkbox del tipo: "create rdfs:label by removing matching prefix" (oppure "create rdfs:label by user input").
In questo caso, se uno inserisce tutta la IRI come input (per esempio perchè non c'è un prefisso corrispondente), allora il label verrà creato con una stringa corrispondente all'iri stessa

**Comment by valeriosantarelli** [comment]
Beh ho aperto una issue lamentandomi del fatto che il sistema fa esattamente quello che dice che fa ahaha...
Comunque si, il comportamento è esattamente quello che descrivi, se uno mette tutta la IRI se la becca tutta nella label. Io userei la dicitura by user input.
