### ISSUE TITLE
Check sintattico aderenza OWL 2 QL non rileva cardinality restriction

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/eddy#91]
Diagrammi contenenti assiomi con cardinality restriction  vengono classificati come aderenti al profilo OWL 2 QL

**Comment by valeriosantarelli** [comment]
Sposto alla milestone 2.2, è bene tenerne traccia, ma non è cruciale al momento.

**Comment by valeriosantarelli** [comment]
Verificare il comportamento anche per le altre restrictions (quindi Self e ForAll).
