### ISSUE TITLE
Question: Using command line application for various tasks

### ISSUE THREAD

**Issue by koslambrou** [obdasystems/eddy#92]
Are there any plans to support a command line application for various tasks using the generated Graphol file such as exporting it to PNG format or Turtle format ?

**Comment by valeriosantarelli** [comment]
Exporting the ontology to all OWL formats, including Turtle, is already supported, as is exporting the ontology diagrams to formats such as png, jpeg, pdf.

Both functionalities are available from the File menu, under Export Ontology and Export Diagrams.
