### ISSUE TITLE
Scrivere documentazione da wikipedia

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/eddy#96]
Sarebbe molto comodo avere un collegamento tra l'editor delle descrizioni e wikipedia perchè la maggior parte delle descrizioni viene da lì. In tal proposito segnalo questa issue che sembra fare al caso nostro:

https://stackoverflow.com/questions/8555320/is-there-a-clean-wikipedia-api-just-for-retrieve-content-summary

https://it.wikipedia.org/api/rest_v1/page/summary/Societ%C3%A0_(diritto)

**Comment by valeriosantarelli** [comment]
Ma se adottiamo concetti di uso comune tale per cui la definizione può essere presa para para da wikipedia, non sarebbe più semplice direttamente utilizzare le ITI di dataset quali wikidata o dbpedia?

O, meglio ancora, e quando possibile, utilizzare i termini definiti da Ontopia nei suoi vocabolari controllati?

Ad esempio, qui sono definite tutte le forme societarie: https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-organizations/legal-status/legal-status.ttl

e mi pare che le IRI siano già tutte dereferenziate, ad esempio: https://ontopia-lodview.pdnd.italia.it/controlled-vocabulary/classifications-for-organizations/legal-status/12

**Comment by valeriosantarelli** [comment]
Teniamo in generale presente che il lavoro di documentazione è estremamente time-consuming, e non abbiamo metodi di aggiornamento automatico delle descrizioni a fronte di modifiche dell'ontologia.
Quindi ogni descrizione che NON scriviamo è tanto di guadagnato per noi.

**Comment by giacomoronconiobda** [comment]
Non mi pare ci siano descrizioni comunque nemmeno in wikidata (in dbpedia non c'è proprio Società di persone). La documentazione è una cosa che non vuole fare nessuno...

**Comment by valeriosantarelli** [comment]
Eh appunto, vediamo di farla il meno possibile noi.

Per dire, il concetto "Stato_di_persona" ha senso che siamo noi a documentarlo, perchè appartiene ad un nostro paradigma di modellazione, e quindi noi lo dobbiamo giustificare.
Ma ad esempio non credo sia nostra responsabilità definire il concetto di "Società di persona", a meno che non siamo noi ad introdurre questo concetto ex-novo nel mondo del semantic web.
Siccome Ontopia ha già definito un set di vocabolari controllati per la pubblica amministrazione, fin quando possibile usiamo quelli. Ovviamente poi possiamo anche aggiungere delle label noi se quelle che usano loro non ci piacciono, ma per le IRI cerchiamo di riusare il riusabile.

https://ontopia-lodview.pdnd.italia.it/controlled-vocabulary/classifications-for-organizations/legal-status/12

**Comment by valeriosantarelli** [comment]
In ogni caso sposto alla 2.2
