### ISSUE TITLE
Estensione del supporto a predicati di metalivello

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#97]
(Su richiesta di Maurizio) Estendere il supporto degli assiomi di metalivello per permettere di definire un arco di instanceOf tra ruoli/attributi e classi.

**Comment by NonnonePalmiro** [comment]
La funzionalità è disponibile nella versione più recente su Drive (per MacOS)

**Comment by valeriosantarelli** [comment]
Confermo, anche l'esportazione in owl mi pare funzioni correttamente.
Chiudo.
