### ISSUE TITLE
Restrizioni diverse da exists

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#98]
Al momento non è possibile salvare restrizioni su dominio o range diverse da "exists".
Ho provato a scrivere una forall, salvare, chiudere il progetto, e riaprirlo, ma torna ad essere un exists.

La segnalazione arriva da una email di Gianluca Pepe del 29/04/2020.
Bisogna credo includere nel file .graphol un riferimento al tipo di restrizione in qualche modo, e, nel caso delle cardinalità, al valore minimo e massimo.

**Comment by NonnonePalmiro** [comment]
Dammi un paio d'ore e committo una patch

**Comment by NonnonePalmiro** [comment]
Su drive c'è una nuova versione che dovrebbe risolvere il problema.

**Comment by valeriosantarelli** [comment]
Ok, mi pare tutto a posto. Chiudo.
