### ISSUE TITLE
OWL HasKey

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#99]
Aggiungere supporto per la definizione di chiavi (assioma HasKey di OWL) nell'ontologia.

E' da capire se e come rappresentare graficamente questo costrutto, intanto apro la issue così ne teniamo traccia (sulla vecchia repository di Redmine c'era, poi è andata persa).

**Comment by valeriosantarelli** [comment]
Questa è la definizione dell'assioma HasKey

HasKey( { A } CE ( OPE1 ... OPEm ) ( DPE1 ... DPEn ) ) where CE is a class expression, OPEi , 1 ≤ i ≤ m are object property expressions DPEj, 1 ≤ j ≤ n are data property expression and { A } zero or more annotations.

**Comment by valeriosantarelli** [comment]
Al build del 24/06/2020 ci sono due problemi:
- si riesce ad agganciare il range di un attributo al nodo key;
- quando si sgancia un nodo agganciato al nodo key, dopo non si riesce più ad agganciare altri nodi. Ad esempio: aggancio una classe e un attributi, sgancio la classe, provo a riagganciare una classe, e non lo fa fare.

Per il resto mi pare stia funzionando tutto bene: l'esportazione in OWL e il check sintattico funzionano quando il nodo è costruito bene.

**Comment by NonnonePalmiro** [comment]
Su bintray c'è la nuova versione, solo per MacOS, che prova a correggere

**Comment by valeriosantarelli** [comment]
Le due problematiche evidenziate sono risolte.
Per il momento chiudo, poi se emerge qualcos'altro vediamo.
